package com.runlion.shop.entity;

import java.util.Date;

/**
 * 
 * CREATE TABLE `bsp_adminuser` ( `uid` int(11) UNSIGNED NOT NULL AUTO_INCREMENT
 * COMMENT '主键' , `username` varchar(50) NULL COMMENT '登录名' , `password`
 * varchar(100) NOT NULL COMMENT '加密后的登录密码' , `salt` char(10) NULL COMMENT '盐值'
 * , `realname` varchar(50) NULL COMMENT '姓名' , `inittime` datetime NULL COMMENT
 * '初始化时间' , `uptime` datetime NULL COMMENT '最后更新时间' , PRIMARY KEY (`uid`) ) ;
 * 
 * @author hsrj05
 *
 */

public class BspAdminuser {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_adminuser.uid
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	private Integer uid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_adminuser.username
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	private String username;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_adminuser.password
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	private String password;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_adminuser.salt
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	private String salt;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_adminuser.realname
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	private String realname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_adminuser.inittime
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	private Date inittime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_adminuser.uptime
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	private Date uptime;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_adminuser.uid
	 *
	 * @return the value of bsp_adminuser.uid
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_adminuser.uid
	 *
	 * @param uid
	 *            the value for bsp_adminuser.uid
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_adminuser.username
	 *
	 * @return the value of bsp_adminuser.username
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_adminuser.username
	 *
	 * @param username
	 *            the value for bsp_adminuser.username
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_adminuser.password
	 *
	 * @return the value of bsp_adminuser.password
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_adminuser.password
	 *
	 * @param password
	 *            the value for bsp_adminuser.password
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_adminuser.salt
	 *
	 * @return the value of bsp_adminuser.salt
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public String getSalt() {
		return salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_adminuser.salt
	 *
	 * @param salt
	 *            the value for bsp_adminuser.salt
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public void setSalt(String salt) {
		this.salt = salt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_adminuser.realname
	 *
	 * @return the value of bsp_adminuser.realname
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public String getRealname() {
		return realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_adminuser.realname
	 *
	 * @param realname
	 *            the value for bsp_adminuser.realname
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public void setRealname(String realname) {
		this.realname = realname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_adminuser.inittime
	 *
	 * @return the value of bsp_adminuser.inittime
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public Date getInittime() {
		return inittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_adminuser.inittime
	 *
	 * @param inittime
	 *            the value for bsp_adminuser.inittime
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public void setInittime(Date inittime) {
		this.inittime = inittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_adminuser.uptime
	 *
	 * @return the value of bsp_adminuser.uptime
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public Date getUptime() {
		return uptime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_adminuser.uptime
	 *
	 * @param uptime
	 *            the value for bsp_adminuser.uptime
	 *
	 * @mbggenerated Mon Jun 29 11:41:53 CST 2015
	 */
	public void setUptime(Date uptime) {
		this.uptime = uptime;
	}
}