package com.runlion.shop.entity;

import java.util.Date;

public class BspAdverts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.adid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer adid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.clickcount
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer clickcount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.adposid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Short adposid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.state
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.starttime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Date starttime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.endtime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Date endtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.displayorder
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer displayorder;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.type
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Byte type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.title
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.url
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String url;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.adid
     *
     * @return the value of bsp_adverts.adid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getAdid() {
        return adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.adid
     *
     * @param adid the value for bsp_adverts.adid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setAdid(Integer adid) {
        this.adid = adid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.clickcount
     *
     * @return the value of bsp_adverts.clickcount
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getClickcount() {
        return clickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.clickcount
     *
     * @param clickcount the value for bsp_adverts.clickcount
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setClickcount(Integer clickcount) {
        this.clickcount = clickcount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.adposid
     *
     * @return the value of bsp_adverts.adposid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Short getAdposid() {
        return adposid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.adposid
     *
     * @param adposid the value for bsp_adverts.adposid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setAdposid(Short adposid) {
        this.adposid = adposid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.state
     *
     * @return the value of bsp_adverts.state
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.state
     *
     * @param state the value for bsp_adverts.state
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.starttime
     *
     * @return the value of bsp_adverts.starttime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Date getStarttime() {
        return starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.starttime
     *
     * @param starttime the value for bsp_adverts.starttime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setStarttime(Date starttime) {
        this.starttime = starttime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.endtime
     *
     * @return the value of bsp_adverts.endtime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Date getEndtime() {
        return endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.endtime
     *
     * @param endtime the value for bsp_adverts.endtime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setEndtime(Date endtime) {
        this.endtime = endtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.displayorder
     *
     * @return the value of bsp_adverts.displayorder
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getDisplayorder() {
        return displayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.displayorder
     *
     * @param displayorder the value for bsp_adverts.displayorder
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setDisplayorder(Integer displayorder) {
        this.displayorder = displayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.type
     *
     * @return the value of bsp_adverts.type
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Byte getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.type
     *
     * @param type the value for bsp_adverts.type
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setType(Byte type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.title
     *
     * @return the value of bsp_adverts.title
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.title
     *
     * @param title the value for bsp_adverts.title
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.url
     *
     * @return the value of bsp_adverts.url
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.url
     *
     * @param url the value for bsp_adverts.url
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setUrl(String url) {
        this.url = url;
    }
}