package com.runlion.shop.entity;

public class BspAdvertsWithBLOBs extends BspAdverts {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.body
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String body;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.extfield1
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String extfield1;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.extfield2
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String extfield2;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.extfield3
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String extfield3;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.extfield4
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String extfield4;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_adverts.extfield5
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String extfield5;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.body
     *
     * @return the value of bsp_adverts.body
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getBody() {
        return body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.body
     *
     * @param body the value for bsp_adverts.body
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setBody(String body) {
        this.body = body;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.extfield1
     *
     * @return the value of bsp_adverts.extfield1
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getExtfield1() {
        return extfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.extfield1
     *
     * @param extfield1 the value for bsp_adverts.extfield1
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setExtfield1(String extfield1) {
        this.extfield1 = extfield1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.extfield2
     *
     * @return the value of bsp_adverts.extfield2
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getExtfield2() {
        return extfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.extfield2
     *
     * @param extfield2 the value for bsp_adverts.extfield2
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setExtfield2(String extfield2) {
        this.extfield2 = extfield2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.extfield3
     *
     * @return the value of bsp_adverts.extfield3
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getExtfield3() {
        return extfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.extfield3
     *
     * @param extfield3 the value for bsp_adverts.extfield3
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setExtfield3(String extfield3) {
        this.extfield3 = extfield3;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.extfield4
     *
     * @return the value of bsp_adverts.extfield4
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getExtfield4() {
        return extfield4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.extfield4
     *
     * @param extfield4 the value for bsp_adverts.extfield4
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setExtfield4(String extfield4) {
        this.extfield4 = extfield4;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_adverts.extfield5
     *
     * @return the value of bsp_adverts.extfield5
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getExtfield5() {
        return extfield5;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_adverts.extfield5
     *
     * @param extfield5 the value for bsp_adverts.extfield5
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setExtfield5(String extfield5) {
        this.extfield5 = extfield5;
    }
}