package com.runlion.shop.entity;

public class BspAttributes {
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_attributes.attrid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Short attrid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_attributes.name
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_attributes.cateid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Short cateid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_attributes.attrgroupid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Short attrgroupid;

	private String attrgroupname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_attributes.showtype
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Byte showtype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_attributes.isfilter
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Byte isfilter;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_attributes.displayorder
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer displayorder;
	/**
	 * sku名字生成时使用的排序
	 */
	private Integer skuorder;

	public Integer getSkuorder() {
		return skuorder;
	}

	public void setSkuorder(Integer skuorder) {
		this.skuorder = skuorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_attributes.attrid
	 *
	 * @return the value of bsp_attributes.attrid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Short getAttrid() {
		return attrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_attributes.attrid
	 *
	 * @param attrid
	 *            the value for bsp_attributes.attrid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setAttrid(Short attrid) {
		this.attrid = attrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_attributes.name
	 *
	 * @return the value of bsp_attributes.name
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_attributes.name
	 *
	 * @param name
	 *            the value for bsp_attributes.name
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_attributes.cateid
	 *
	 * @return the value of bsp_attributes.cateid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Short getCateid() {
		return cateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_attributes.cateid
	 *
	 * @param cateid
	 *            the value for bsp_attributes.cateid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setCateid(Short cateid) {
		this.cateid = cateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_attributes.attrgroupid
	 *
	 * @return the value of bsp_attributes.attrgroupid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Short getAttrgroupid() {
		return attrgroupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_attributes.attrgroupid
	 *
	 * @param attrgroupid
	 *            the value for bsp_attributes.attrgroupid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setAttrgroupid(Short attrgroupid) {
		this.attrgroupid = attrgroupid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_attributes.showtype
	 *
	 * @return the value of bsp_attributes.showtype
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Byte getShowtype() {
		return showtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_attributes.showtype
	 *
	 * @param showtype
	 *            the value for bsp_attributes.showtype
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setShowtype(Byte showtype) {
		this.showtype = showtype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_attributes.isfilter
	 *
	 * @return the value of bsp_attributes.isfilter
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Byte getIsfilter() {
		return isfilter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_attributes.isfilter
	 *
	 * @param isfilter
	 *            the value for bsp_attributes.isfilter
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setIsfilter(Byte isfilter) {
		this.isfilter = isfilter;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_attributes.displayorder
	 *
	 * @return the value of bsp_attributes.displayorder
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getDisplayorder() {
		return displayorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_attributes.displayorder
	 *
	 * @param displayorder
	 *            the value for bsp_attributes.displayorder
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setDisplayorder(Integer displayorder) {
		this.displayorder = displayorder;
	}

	public String getAttrgroupname() {
		return attrgroupname;
	}

	public void setAttrgroupname(String attrgroupname) {
		this.attrgroupname = attrgroupname;
	}

}