package com.runlion.shop.entity;

import java.util.Date;

public class BspCancelorderReason {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_cancelOrder_reason.id
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_cancelOrder_reason.oid
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_cancelOrder_reason.reasonid
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    private Integer reasonid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_cancelOrder_reason.reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    private String reason;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_cancelOrder_reason.createTime
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    private Date createtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_cancelOrder_reason.uid
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_cancelOrder_reason.description
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    private String description;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_cancelOrder_reason.id
     *
     * @return the value of bsp_cancelOrder_reason.id
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_cancelOrder_reason.id
     *
     * @param id the value for bsp_cancelOrder_reason.id
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_cancelOrder_reason.oid
     *
     * @return the value of bsp_cancelOrder_reason.oid
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_cancelOrder_reason.oid
     *
     * @param oid the value for bsp_cancelOrder_reason.oid
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_cancelOrder_reason.reasonid
     *
     * @return the value of bsp_cancelOrder_reason.reasonid
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public Integer getReasonid() {
        return reasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_cancelOrder_reason.reasonid
     *
     * @param reasonid the value for bsp_cancelOrder_reason.reasonid
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public void setReasonid(Integer reasonid) {
        this.reasonid = reasonid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_cancelOrder_reason.reason
     *
     * @return the value of bsp_cancelOrder_reason.reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_cancelOrder_reason.reason
     *
     * @param reason the value for bsp_cancelOrder_reason.reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public void setReason(String reason) {
        this.reason = reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_cancelOrder_reason.createTime
     *
     * @return the value of bsp_cancelOrder_reason.createTime
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_cancelOrder_reason.createTime
     *
     * @param createtime the value for bsp_cancelOrder_reason.createTime
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_cancelOrder_reason.uid
     *
     * @return the value of bsp_cancelOrder_reason.uid
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_cancelOrder_reason.uid
     *
     * @param uid the value for bsp_cancelOrder_reason.uid
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_cancelOrder_reason.description
     *
     * @return the value of bsp_cancelOrder_reason.description
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public String getDescription() {
        return description;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_cancelOrder_reason.description
     *
     * @param description the value for bsp_cancelOrder_reason.description
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    public void setDescription(String description) {
        this.description = description;
    }
}