package com.runlion.shop.entity;

import java.util.Date;

public class BspFavorites {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_favorites.recordid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer recordid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_favorites.uid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_favorites.pid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_favorites.state
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_favorites.addtime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Date addtime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_favorites.recordid
     *
     * @return the value of bsp_favorites.recordid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getRecordid() {
        return recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_favorites.recordid
     *
     * @param recordid the value for bsp_favorites.recordid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setRecordid(Integer recordid) {
        this.recordid = recordid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_favorites.uid
     *
     * @return the value of bsp_favorites.uid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_favorites.uid
     *
     * @param uid the value for bsp_favorites.uid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_favorites.pid
     *
     * @return the value of bsp_favorites.pid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_favorites.pid
     *
     * @param pid the value for bsp_favorites.pid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_favorites.state
     *
     * @return the value of bsp_favorites.state
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_favorites.state
     *
     * @param state the value for bsp_favorites.state
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_favorites.addtime
     *
     * @return the value of bsp_favorites.addtime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Date getAddtime() {
        return addtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_favorites.addtime
     *
     * @param addtime the value for bsp_favorites.addtime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setAddtime(Date addtime) {
        this.addtime = addtime;
    }
    
    private BspProducts product;

	public BspProducts getProduct() {
		return product;
	}

	public void setProduct(BspProducts product) {
		this.product = product;
	}
}