package com.runlion.shop.entity;

import java.util.Date;

public class BspInvoice {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private Integer invid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.oid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invtype
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invtype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invtitle
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invtitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invcontent
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invcontent;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invcomname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invcomname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invtaxnum
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invtaxnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invaddress
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invaddress;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invtel
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invtel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invbankno
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invbankno;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invbankname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invbankname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invrecname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invrecname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invrectel
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invrectel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.regionid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private Integer regionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.regioncid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String regioncid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.regionname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String regionname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.invdetailaddr
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String invdetailaddr;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.inittime
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private Date inittime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.uptime
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private Date uptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.shiptype
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private Integer shiptype;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_invoice.shipaddress
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    private String shipaddress;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invid
     *
     * @return the value of bsp_invoice.invid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public Integer getInvid() {
        return invid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invid
     *
     * @param invid the value for bsp_invoice.invid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvid(Integer invid) {
        this.invid = invid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.oid
     *
     * @return the value of bsp_invoice.oid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.oid
     *
     * @param oid the value for bsp_invoice.oid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invtype
     *
     * @return the value of bsp_invoice.invtype
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvtype() {
        return invtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invtype
     *
     * @param invtype the value for bsp_invoice.invtype
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvtype(String invtype) {
        this.invtype = invtype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invtitle
     *
     * @return the value of bsp_invoice.invtitle
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvtitle() {
        return invtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invtitle
     *
     * @param invtitle the value for bsp_invoice.invtitle
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvtitle(String invtitle) {
        this.invtitle = invtitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invcontent
     *
     * @return the value of bsp_invoice.invcontent
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvcontent() {
        return invcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invcontent
     *
     * @param invcontent the value for bsp_invoice.invcontent
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvcontent(String invcontent) {
        this.invcontent = invcontent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invcomname
     *
     * @return the value of bsp_invoice.invcomname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvcomname() {
        return invcomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invcomname
     *
     * @param invcomname the value for bsp_invoice.invcomname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvcomname(String invcomname) {
        this.invcomname = invcomname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invtaxnum
     *
     * @return the value of bsp_invoice.invtaxnum
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvtaxnum() {
        return invtaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invtaxnum
     *
     * @param invtaxnum the value for bsp_invoice.invtaxnum
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvtaxnum(String invtaxnum) {
        this.invtaxnum = invtaxnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invaddress
     *
     * @return the value of bsp_invoice.invaddress
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvaddress() {
        return invaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invaddress
     *
     * @param invaddress the value for bsp_invoice.invaddress
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvaddress(String invaddress) {
        this.invaddress = invaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invtel
     *
     * @return the value of bsp_invoice.invtel
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvtel() {
        return invtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invtel
     *
     * @param invtel the value for bsp_invoice.invtel
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvtel(String invtel) {
        this.invtel = invtel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invbankno
     *
     * @return the value of bsp_invoice.invbankno
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvbankno() {
        return invbankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invbankno
     *
     * @param invbankno the value for bsp_invoice.invbankno
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvbankno(String invbankno) {
        this.invbankno = invbankno;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invbankname
     *
     * @return the value of bsp_invoice.invbankname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvbankname() {
        return invbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invbankname
     *
     * @param invbankname the value for bsp_invoice.invbankname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvbankname(String invbankname) {
        this.invbankname = invbankname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invrecname
     *
     * @return the value of bsp_invoice.invrecname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvrecname() {
        return invrecname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invrecname
     *
     * @param invrecname the value for bsp_invoice.invrecname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvrecname(String invrecname) {
        this.invrecname = invrecname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invrectel
     *
     * @return the value of bsp_invoice.invrectel
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvrectel() {
        return invrectel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invrectel
     *
     * @param invrectel the value for bsp_invoice.invrectel
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvrectel(String invrectel) {
        this.invrectel = invrectel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.regionid
     *
     * @return the value of bsp_invoice.regionid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public Integer getRegionid() {
        return regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.regionid
     *
     * @param regionid the value for bsp_invoice.regionid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setRegionid(Integer regionid) {
        this.regionid = regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.regioncid
     *
     * @return the value of bsp_invoice.regioncid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getRegioncid() {
        return regioncid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.regioncid
     *
     * @param regioncid the value for bsp_invoice.regioncid
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setRegioncid(String regioncid) {
        this.regioncid = regioncid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.regionname
     *
     * @return the value of bsp_invoice.regionname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getRegionname() {
        return regionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.regionname
     *
     * @param regionname the value for bsp_invoice.regionname
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setRegionname(String regionname) {
        this.regionname = regionname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.invdetailaddr
     *
     * @return the value of bsp_invoice.invdetailaddr
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getInvdetailaddr() {
        return invdetailaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.invdetailaddr
     *
     * @param invdetailaddr the value for bsp_invoice.invdetailaddr
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInvdetailaddr(String invdetailaddr) {
        this.invdetailaddr = invdetailaddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.inittime
     *
     * @return the value of bsp_invoice.inittime
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public Date getInittime() {
        return inittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.inittime
     *
     * @param inittime the value for bsp_invoice.inittime
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setInittime(Date inittime) {
        this.inittime = inittime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.uptime
     *
     * @return the value of bsp_invoice.uptime
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public Date getUptime() {
        return uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.uptime
     *
     * @param uptime the value for bsp_invoice.uptime
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setUptime(Date uptime) {
        this.uptime = uptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.shiptype
     *
     * @return the value of bsp_invoice.shiptype
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public Integer getShiptype() {
        return shiptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.shiptype
     *
     * @param shiptype the value for bsp_invoice.shiptype
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setShiptype(Integer shiptype) {
        this.shiptype = shiptype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_invoice.shipaddress
     *
     * @return the value of bsp_invoice.shipaddress
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public String getShipaddress() {
        return shipaddress;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_invoice.shipaddress
     *
     * @param shipaddress the value for bsp_invoice.shipaddress
     *
     * @mbggenerated Thu Sep 24 09:29:09 CST 2015
     */
    public void setShipaddress(String shipaddress) {
        this.shipaddress = shipaddress;
    }
}