package com.runlion.shop.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BspOrderpricemnyExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public BspOrderpricemnyExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andOidIsNull() {
            addCriterion("oid is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("oid is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(Integer value) {
            addCriterion("oid =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(Integer value) {
            addCriterion("oid <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(Integer value) {
            addCriterion("oid >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(Integer value) {
            addCriterion("oid >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(Integer value) {
            addCriterion("oid <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(Integer value) {
            addCriterion("oid <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<Integer> values) {
            addCriterion("oid in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<Integer> values) {
            addCriterion("oid not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(Integer value1, Integer value2) {
            addCriterion("oid between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(Integer value1, Integer value2) {
            addCriterion("oid not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNull() {
            addCriterion("paytype is null");
            return (Criteria) this;
        }

        public Criteria andPaytypeIsNotNull() {
            addCriterion("paytype is not null");
            return (Criteria) this;
        }

        public Criteria andPaytypeEqualTo(Byte value) {
            addCriterion("paytype =", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotEqualTo(Byte value) {
            addCriterion("paytype <>", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThan(Byte value) {
            addCriterion("paytype >", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("paytype >=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThan(Byte value) {
            addCriterion("paytype <", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeLessThanOrEqualTo(Byte value) {
            addCriterion("paytype <=", value, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeIn(List<Byte> values) {
            addCriterion("paytype in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotIn(List<Byte> values) {
            addCriterion("paytype not in", values, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeBetween(Byte value1, Byte value2) {
            addCriterion("paytype between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaytypeNotBetween(Byte value1, Byte value2) {
            addCriterion("paytype not between", value1, value2, "paytype");
            return (Criteria) this;
        }

        public Criteria andPaypriceIsNull() {
            addCriterion("payprice is null");
            return (Criteria) this;
        }

        public Criteria andPaypriceIsNotNull() {
            addCriterion("payprice is not null");
            return (Criteria) this;
        }

        public Criteria andPaypriceEqualTo(BigDecimal value) {
            addCriterion("payprice =", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceNotEqualTo(BigDecimal value) {
            addCriterion("payprice <>", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceGreaterThan(BigDecimal value) {
            addCriterion("payprice >", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("payprice >=", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceLessThan(BigDecimal value) {
            addCriterion("payprice <", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceLessThanOrEqualTo(BigDecimal value) {
            addCriterion("payprice <=", value, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceIn(List<BigDecimal> values) {
            addCriterion("payprice in", values, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceNotIn(List<BigDecimal> values) {
            addCriterion("payprice not in", values, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("payprice between", value1, value2, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaypriceNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("payprice not between", value1, value2, "payprice");
            return (Criteria) this;
        }

        public Criteria andPaysummnyIsNull() {
            addCriterion("paysummny is null");
            return (Criteria) this;
        }

        public Criteria andPaysummnyIsNotNull() {
            addCriterion("paysummny is not null");
            return (Criteria) this;
        }

        public Criteria andPaysummnyEqualTo(BigDecimal value) {
            addCriterion("paysummny =", value, "paysummny");
            return (Criteria) this;
        }

        public Criteria andPaysummnyNotEqualTo(BigDecimal value) {
            addCriterion("paysummny <>", value, "paysummny");
            return (Criteria) this;
        }

        public Criteria andPaysummnyGreaterThan(BigDecimal value) {
            addCriterion("paysummny >", value, "paysummny");
            return (Criteria) this;
        }

        public Criteria andPaysummnyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("paysummny >=", value, "paysummny");
            return (Criteria) this;
        }

        public Criteria andPaysummnyLessThan(BigDecimal value) {
            addCriterion("paysummny <", value, "paysummny");
            return (Criteria) this;
        }

        public Criteria andPaysummnyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("paysummny <=", value, "paysummny");
            return (Criteria) this;
        }

        public Criteria andPaysummnyIn(List<BigDecimal> values) {
            addCriterion("paysummny in", values, "paysummny");
            return (Criteria) this;
        }

        public Criteria andPaysummnyNotIn(List<BigDecimal> values) {
            addCriterion("paysummny not in", values, "paysummny");
            return (Criteria) this;
        }

        public Criteria andPaysummnyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paysummny between", value1, value2, "paysummny");
            return (Criteria) this;
        }

        public Criteria andPaysummnyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("paysummny not between", value1, value2, "paysummny");
            return (Criteria) this;
        }

        public Criteria andUptimeIsNull() {
            addCriterion("uptime is null");
            return (Criteria) this;
        }

        public Criteria andUptimeIsNotNull() {
            addCriterion("uptime is not null");
            return (Criteria) this;
        }

        public Criteria andUptimeEqualTo(Date value) {
            addCriterion("uptime =", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeNotEqualTo(Date value) {
            addCriterion("uptime <>", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeGreaterThan(Date value) {
            addCriterion("uptime >", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeGreaterThanOrEqualTo(Date value) {
            addCriterion("uptime >=", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeLessThan(Date value) {
            addCriterion("uptime <", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeLessThanOrEqualTo(Date value) {
            addCriterion("uptime <=", value, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeIn(List<Date> values) {
            addCriterion("uptime in", values, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeNotIn(List<Date> values) {
            addCriterion("uptime not in", values, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeBetween(Date value1, Date value2) {
            addCriterion("uptime between", value1, value2, "uptime");
            return (Criteria) this;
        }

        public Criteria andUptimeNotBetween(Date value1, Date value2) {
            addCriterion("uptime not between", value1, value2, "uptime");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andExtinfor1IsNull() {
            addCriterion("extinfor1 is null");
            return (Criteria) this;
        }

        public Criteria andExtinfor1IsNotNull() {
            addCriterion("extinfor1 is not null");
            return (Criteria) this;
        }

        public Criteria andExtinfor1EqualTo(String value) {
            addCriterion("extinfor1 =", value, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1NotEqualTo(String value) {
            addCriterion("extinfor1 <>", value, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1GreaterThan(String value) {
            addCriterion("extinfor1 >", value, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1GreaterThanOrEqualTo(String value) {
            addCriterion("extinfor1 >=", value, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1LessThan(String value) {
            addCriterion("extinfor1 <", value, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1LessThanOrEqualTo(String value) {
            addCriterion("extinfor1 <=", value, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1Like(String value) {
            addCriterion("extinfor1 like", value, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1NotLike(String value) {
            addCriterion("extinfor1 not like", value, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1In(List<String> values) {
            addCriterion("extinfor1 in", values, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1NotIn(List<String> values) {
            addCriterion("extinfor1 not in", values, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1Between(String value1, String value2) {
            addCriterion("extinfor1 between", value1, value2, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor1NotBetween(String value1, String value2) {
            addCriterion("extinfor1 not between", value1, value2, "extinfor1");
            return (Criteria) this;
        }

        public Criteria andExtinfor2IsNull() {
            addCriterion("extinfor2 is null");
            return (Criteria) this;
        }

        public Criteria andExtinfor2IsNotNull() {
            addCriterion("extinfor2 is not null");
            return (Criteria) this;
        }

        public Criteria andExtinfor2EqualTo(String value) {
            addCriterion("extinfor2 =", value, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2NotEqualTo(String value) {
            addCriterion("extinfor2 <>", value, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2GreaterThan(String value) {
            addCriterion("extinfor2 >", value, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2GreaterThanOrEqualTo(String value) {
            addCriterion("extinfor2 >=", value, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2LessThan(String value) {
            addCriterion("extinfor2 <", value, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2LessThanOrEqualTo(String value) {
            addCriterion("extinfor2 <=", value, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2Like(String value) {
            addCriterion("extinfor2 like", value, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2NotLike(String value) {
            addCriterion("extinfor2 not like", value, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2In(List<String> values) {
            addCriterion("extinfor2 in", values, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2NotIn(List<String> values) {
            addCriterion("extinfor2 not in", values, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2Between(String value1, String value2) {
            addCriterion("extinfor2 between", value1, value2, "extinfor2");
            return (Criteria) this;
        }

        public Criteria andExtinfor2NotBetween(String value1, String value2) {
            addCriterion("extinfor2 not between", value1, value2, "extinfor2");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated do_not_delete_during_merge Wed Sep 09 16:48:51 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}