package com.runlion.shop.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class BspOrderactionsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public BspOrderactionsExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andAidIsNull() {
            addCriterion("aid is null");
            return (Criteria) this;
        }

        public Criteria andAidIsNotNull() {
            addCriterion("aid is not null");
            return (Criteria) this;
        }

        public Criteria andAidEqualTo(Integer value) {
            addCriterion("aid =", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotEqualTo(Integer value) {
            addCriterion("aid <>", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThan(Integer value) {
            addCriterion("aid >", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidGreaterThanOrEqualTo(Integer value) {
            addCriterion("aid >=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThan(Integer value) {
            addCriterion("aid <", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidLessThanOrEqualTo(Integer value) {
            addCriterion("aid <=", value, "aid");
            return (Criteria) this;
        }

        public Criteria andAidIn(List<Integer> values) {
            addCriterion("aid in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotIn(List<Integer> values) {
            addCriterion("aid not in", values, "aid");
            return (Criteria) this;
        }

        public Criteria andAidBetween(Integer value1, Integer value2) {
            addCriterion("aid between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andAidNotBetween(Integer value1, Integer value2) {
            addCriterion("aid not between", value1, value2, "aid");
            return (Criteria) this;
        }

        public Criteria andOidIsNull() {
            addCriterion("oid is null");
            return (Criteria) this;
        }

        public Criteria andOidIsNotNull() {
            addCriterion("oid is not null");
            return (Criteria) this;
        }

        public Criteria andOidEqualTo(Integer value) {
            addCriterion("oid =", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotEqualTo(Integer value) {
            addCriterion("oid <>", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThan(Integer value) {
            addCriterion("oid >", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidGreaterThanOrEqualTo(Integer value) {
            addCriterion("oid >=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThan(Integer value) {
            addCriterion("oid <", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidLessThanOrEqualTo(Integer value) {
            addCriterion("oid <=", value, "oid");
            return (Criteria) this;
        }

        public Criteria andOidIn(List<Integer> values) {
            addCriterion("oid in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotIn(List<Integer> values) {
            addCriterion("oid not in", values, "oid");
            return (Criteria) this;
        }

        public Criteria andOidBetween(Integer value1, Integer value2) {
            addCriterion("oid between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andOidNotBetween(Integer value1, Integer value2) {
            addCriterion("oid not between", value1, value2, "oid");
            return (Criteria) this;
        }

        public Criteria andUidIsNull() {
            addCriterion("uid is null");
            return (Criteria) this;
        }

        public Criteria andUidIsNotNull() {
            addCriterion("uid is not null");
            return (Criteria) this;
        }

        public Criteria andUidEqualTo(Integer value) {
            addCriterion("uid =", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotEqualTo(Integer value) {
            addCriterion("uid <>", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThan(Integer value) {
            addCriterion("uid >", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidGreaterThanOrEqualTo(Integer value) {
            addCriterion("uid >=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThan(Integer value) {
            addCriterion("uid <", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidLessThanOrEqualTo(Integer value) {
            addCriterion("uid <=", value, "uid");
            return (Criteria) this;
        }

        public Criteria andUidIn(List<Integer> values) {
            addCriterion("uid in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotIn(List<Integer> values) {
            addCriterion("uid not in", values, "uid");
            return (Criteria) this;
        }

        public Criteria andUidBetween(Integer value1, Integer value2) {
            addCriterion("uid between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andUidNotBetween(Integer value1, Integer value2) {
            addCriterion("uid not between", value1, value2, "uid");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNull() {
            addCriterion("realname is null");
            return (Criteria) this;
        }

        public Criteria andRealnameIsNotNull() {
            addCriterion("realname is not null");
            return (Criteria) this;
        }

        public Criteria andRealnameEqualTo(String value) {
            addCriterion("realname =", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotEqualTo(String value) {
            addCriterion("realname <>", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThan(String value) {
            addCriterion("realname >", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameGreaterThanOrEqualTo(String value) {
            addCriterion("realname >=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThan(String value) {
            addCriterion("realname <", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLessThanOrEqualTo(String value) {
            addCriterion("realname <=", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameLike(String value) {
            addCriterion("realname like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotLike(String value) {
            addCriterion("realname not like", value, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameIn(List<String> values) {
            addCriterion("realname in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotIn(List<String> values) {
            addCriterion("realname not in", values, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameBetween(String value1, String value2) {
            addCriterion("realname between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andRealnameNotBetween(String value1, String value2) {
            addCriterion("realname not between", value1, value2, "realname");
            return (Criteria) this;
        }

        public Criteria andAdmingidIsNull() {
            addCriterion("admingid is null");
            return (Criteria) this;
        }

        public Criteria andAdmingidIsNotNull() {
            addCriterion("admingid is not null");
            return (Criteria) this;
        }

        public Criteria andAdmingidEqualTo(Short value) {
            addCriterion("admingid =", value, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingidNotEqualTo(Short value) {
            addCriterion("admingid <>", value, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingidGreaterThan(Short value) {
            addCriterion("admingid >", value, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingidGreaterThanOrEqualTo(Short value) {
            addCriterion("admingid >=", value, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingidLessThan(Short value) {
            addCriterion("admingid <", value, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingidLessThanOrEqualTo(Short value) {
            addCriterion("admingid <=", value, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingidIn(List<Short> values) {
            addCriterion("admingid in", values, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingidNotIn(List<Short> values) {
            addCriterion("admingid not in", values, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingidBetween(Short value1, Short value2) {
            addCriterion("admingid between", value1, value2, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingidNotBetween(Short value1, Short value2) {
            addCriterion("admingid not between", value1, value2, "admingid");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleIsNull() {
            addCriterion("admingtitle is null");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleIsNotNull() {
            addCriterion("admingtitle is not null");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleEqualTo(String value) {
            addCriterion("admingtitle =", value, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleNotEqualTo(String value) {
            addCriterion("admingtitle <>", value, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleGreaterThan(String value) {
            addCriterion("admingtitle >", value, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleGreaterThanOrEqualTo(String value) {
            addCriterion("admingtitle >=", value, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleLessThan(String value) {
            addCriterion("admingtitle <", value, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleLessThanOrEqualTo(String value) {
            addCriterion("admingtitle <=", value, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleLike(String value) {
            addCriterion("admingtitle like", value, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleNotLike(String value) {
            addCriterion("admingtitle not like", value, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleIn(List<String> values) {
            addCriterion("admingtitle in", values, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleNotIn(List<String> values) {
            addCriterion("admingtitle not in", values, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleBetween(String value1, String value2) {
            addCriterion("admingtitle between", value1, value2, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andAdmingtitleNotBetween(String value1, String value2) {
            addCriterion("admingtitle not between", value1, value2, "admingtitle");
            return (Criteria) this;
        }

        public Criteria andActiontypeIsNull() {
            addCriterion("actiontype is null");
            return (Criteria) this;
        }

        public Criteria andActiontypeIsNotNull() {
            addCriterion("actiontype is not null");
            return (Criteria) this;
        }

        public Criteria andActiontypeEqualTo(Byte value) {
            addCriterion("actiontype =", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeNotEqualTo(Byte value) {
            addCriterion("actiontype <>", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeGreaterThan(Byte value) {
            addCriterion("actiontype >", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeGreaterThanOrEqualTo(Byte value) {
            addCriterion("actiontype >=", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeLessThan(Byte value) {
            addCriterion("actiontype <", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeLessThanOrEqualTo(Byte value) {
            addCriterion("actiontype <=", value, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeIn(List<Byte> values) {
            addCriterion("actiontype in", values, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeNotIn(List<Byte> values) {
            addCriterion("actiontype not in", values, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeBetween(Byte value1, Byte value2) {
            addCriterion("actiontype between", value1, value2, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontypeNotBetween(Byte value1, Byte value2) {
            addCriterion("actiontype not between", value1, value2, "actiontype");
            return (Criteria) this;
        }

        public Criteria andActiontimeIsNull() {
            addCriterion("actiontime is null");
            return (Criteria) this;
        }

        public Criteria andActiontimeIsNotNull() {
            addCriterion("actiontime is not null");
            return (Criteria) this;
        }

        public Criteria andActiontimeEqualTo(Date value) {
            addCriterion("actiontime =", value, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiontimeNotEqualTo(Date value) {
            addCriterion("actiontime <>", value, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiontimeGreaterThan(Date value) {
            addCriterion("actiontime >", value, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiontimeGreaterThanOrEqualTo(Date value) {
            addCriterion("actiontime >=", value, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiontimeLessThan(Date value) {
            addCriterion("actiontime <", value, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiontimeLessThanOrEqualTo(Date value) {
            addCriterion("actiontime <=", value, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiontimeIn(List<Date> values) {
            addCriterion("actiontime in", values, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiontimeNotIn(List<Date> values) {
            addCriterion("actiontime not in", values, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiontimeBetween(Date value1, Date value2) {
            addCriterion("actiontime between", value1, value2, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiontimeNotBetween(Date value1, Date value2) {
            addCriterion("actiontime not between", value1, value2, "actiontime");
            return (Criteria) this;
        }

        public Criteria andActiondesIsNull() {
            addCriterion("actiondes is null");
            return (Criteria) this;
        }

        public Criteria andActiondesIsNotNull() {
            addCriterion("actiondes is not null");
            return (Criteria) this;
        }

        public Criteria andActiondesEqualTo(String value) {
            addCriterion("actiondes =", value, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesNotEqualTo(String value) {
            addCriterion("actiondes <>", value, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesGreaterThan(String value) {
            addCriterion("actiondes >", value, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesGreaterThanOrEqualTo(String value) {
            addCriterion("actiondes >=", value, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesLessThan(String value) {
            addCriterion("actiondes <", value, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesLessThanOrEqualTo(String value) {
            addCriterion("actiondes <=", value, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesLike(String value) {
            addCriterion("actiondes like", value, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesNotLike(String value) {
            addCriterion("actiondes not like", value, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesIn(List<String> values) {
            addCriterion("actiondes in", values, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesNotIn(List<String> values) {
            addCriterion("actiondes not in", values, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesBetween(String value1, String value2) {
            addCriterion("actiondes between", value1, value2, "actiondes");
            return (Criteria) this;
        }

        public Criteria andActiondesNotBetween(String value1, String value2) {
            addCriterion("actiondes not between", value1, value2, "actiondes");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_orderactions
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 26 14:56:27 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_orderactions
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}