package com.runlion.shop.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BspOrderproducts {

	private Integer isExists = 1; // 商品是否已经下架 1：在售， 0：下架

	public Integer getIsExists() {
		return isExists;
	}

	public void setIsExists(Integer isExists) {
		this.isExists = isExists;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.recordid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer recordid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.oid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer oid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.uid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer uid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.sid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private String sid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.pid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer pid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.psn
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private String psn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.cateid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Short cateid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.brandid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer brandid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.name
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.showimg
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private String showimg;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.discountprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private BigDecimal discountprice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.shopprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private BigDecimal shopprice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.costprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private BigDecimal costprice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.marketprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private BigDecimal marketprice;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.weight
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Float weight;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.isreview
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Byte isreview;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.realcount
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Double realcount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.buycount
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Double buycount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.sendcount
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Double sendcount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.type
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Byte type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.paycredits
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer paycredits;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.coupontypeid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer coupontypeid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.extcode1
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer extcode1;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.extcode2
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer extcode2;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.extcode3
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer extcode3;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.extcode4
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer extcode4;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.extcode5
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Integer extcode5;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.addtime
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private Date addtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.url
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private String url;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.itemtotalmny
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private BigDecimal itemtotalmny;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.shipmny
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private BigDecimal shipmny;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.handmny
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private BigDecimal handmny;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orderproducts.sendBatch
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	private String sendbatch;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.recordid
	 *
	 * @return the value of bsp_orderproducts.recordid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getRecordid() {
		return recordid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.recordid
	 *
	 * @param recordid
	 *            the value for bsp_orderproducts.recordid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setRecordid(Integer recordid) {
		this.recordid = recordid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.oid
	 *
	 * @return the value of bsp_orderproducts.oid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.oid
	 *
	 * @param oid
	 *            the value for bsp_orderproducts.oid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setOid(Integer oid) {
		this.oid = oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.uid
	 *
	 * @return the value of bsp_orderproducts.uid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.uid
	 *
	 * @param uid
	 *            the value for bsp_orderproducts.uid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.sid
	 *
	 * @return the value of bsp_orderproducts.sid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public String getSid() {
		return sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.sid
	 *
	 * @param sid
	 *            the value for bsp_orderproducts.sid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setSid(String sid) {
		this.sid = sid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.pid
	 *
	 * @return the value of bsp_orderproducts.pid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.pid
	 *
	 * @param pid
	 *            the value for bsp_orderproducts.pid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.psn
	 *
	 * @return the value of bsp_orderproducts.psn
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public String getPsn() {
		return psn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.psn
	 *
	 * @param psn
	 *            the value for bsp_orderproducts.psn
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setPsn(String psn) {
		this.psn = psn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.cateid
	 *
	 * @return the value of bsp_orderproducts.cateid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Short getCateid() {
		return cateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.cateid
	 *
	 * @param cateid
	 *            the value for bsp_orderproducts.cateid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setCateid(Short cateid) {
		this.cateid = cateid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.brandid
	 *
	 * @return the value of bsp_orderproducts.brandid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getBrandid() {
		return brandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.brandid
	 *
	 * @param brandid
	 *            the value for bsp_orderproducts.brandid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setBrandid(Integer brandid) {
		this.brandid = brandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.name
	 *
	 * @return the value of bsp_orderproducts.name
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.name
	 *
	 * @param name
	 *            the value for bsp_orderproducts.name
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.showimg
	 *
	 * @return the value of bsp_orderproducts.showimg
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public String getShowimg() {
		return showimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.showimg
	 *
	 * @param showimg
	 *            the value for bsp_orderproducts.showimg
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setShowimg(String showimg) {
		this.showimg = showimg;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.discountprice
	 *
	 * @return the value of bsp_orderproducts.discountprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public BigDecimal getDiscountprice() {
		return discountprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.discountprice
	 *
	 * @param discountprice
	 *            the value for bsp_orderproducts.discountprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setDiscountprice(BigDecimal discountprice) {
		this.discountprice = discountprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.shopprice
	 *
	 * @return the value of bsp_orderproducts.shopprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public BigDecimal getShopprice() {
		return shopprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.shopprice
	 *
	 * @param shopprice
	 *            the value for bsp_orderproducts.shopprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setShopprice(BigDecimal shopprice) {
		this.shopprice = shopprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.costprice
	 *
	 * @return the value of bsp_orderproducts.costprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public BigDecimal getCostprice() {
		return costprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.costprice
	 *
	 * @param costprice
	 *            the value for bsp_orderproducts.costprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setCostprice(BigDecimal costprice) {
		this.costprice = costprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.marketprice
	 *
	 * @return the value of bsp_orderproducts.marketprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public BigDecimal getMarketprice() {
		return marketprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.marketprice
	 *
	 * @param marketprice
	 *            the value for bsp_orderproducts.marketprice
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setMarketprice(BigDecimal marketprice) {
		this.marketprice = marketprice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.weight
	 *
	 * @return the value of bsp_orderproducts.weight
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Float getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.weight
	 *
	 * @param weight
	 *            the value for bsp_orderproducts.weight
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setWeight(Float weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.isreview
	 *
	 * @return the value of bsp_orderproducts.isreview
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Byte getIsreview() {
		return isreview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.isreview
	 *
	 * @param isreview
	 *            the value for bsp_orderproducts.isreview
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setIsreview(Byte isreview) {
		this.isreview = isreview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.realcount
	 *
	 * @return the value of bsp_orderproducts.realcount
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Double getRealcount() {
		return realcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.realcount
	 *
	 * @param realcount
	 *            the value for bsp_orderproducts.realcount
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setRealcount(Double realcount) {
		this.realcount = realcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.buycount
	 *
	 * @return the value of bsp_orderproducts.buycount
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Double getBuycount() {
		return buycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.buycount
	 *
	 * @param buycount
	 *            the value for bsp_orderproducts.buycount
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setBuycount(Double buycount) {
		this.buycount = buycount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.sendcount
	 *
	 * @return the value of bsp_orderproducts.sendcount
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Double getSendcount() {
		return sendcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.sendcount
	 *
	 * @param sendcount
	 *            the value for bsp_orderproducts.sendcount
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setSendcount(Double sendcount) {
		this.sendcount = sendcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.type
	 *
	 * @return the value of bsp_orderproducts.type
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Byte getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.type
	 *
	 * @param type
	 *            the value for bsp_orderproducts.type
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setType(Byte type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.paycredits
	 *
	 * @return the value of bsp_orderproducts.paycredits
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getPaycredits() {
		return paycredits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.paycredits
	 *
	 * @param paycredits
	 *            the value for bsp_orderproducts.paycredits
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setPaycredits(Integer paycredits) {
		this.paycredits = paycredits;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.coupontypeid
	 *
	 * @return the value of bsp_orderproducts.coupontypeid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getCoupontypeid() {
		return coupontypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.coupontypeid
	 *
	 * @param coupontypeid
	 *            the value for bsp_orderproducts.coupontypeid
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setCoupontypeid(Integer coupontypeid) {
		this.coupontypeid = coupontypeid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.extcode1
	 *
	 * @return the value of bsp_orderproducts.extcode1
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getExtcode1() {
		return extcode1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.extcode1
	 *
	 * @param extcode1
	 *            the value for bsp_orderproducts.extcode1
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setExtcode1(Integer extcode1) {
		this.extcode1 = extcode1;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.extcode2
	 *
	 * @return the value of bsp_orderproducts.extcode2
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getExtcode2() {
		return extcode2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.extcode2
	 *
	 * @param extcode2
	 *            the value for bsp_orderproducts.extcode2
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setExtcode2(Integer extcode2) {
		this.extcode2 = extcode2;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.extcode3
	 *
	 * @return the value of bsp_orderproducts.extcode3
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getExtcode3() {
		return extcode3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.extcode3
	 *
	 * @param extcode3
	 *            the value for bsp_orderproducts.extcode3
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setExtcode3(Integer extcode3) {
		this.extcode3 = extcode3;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.extcode4
	 *
	 * @return the value of bsp_orderproducts.extcode4
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getExtcode4() {
		return extcode4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.extcode4
	 *
	 * @param extcode4
	 *            the value for bsp_orderproducts.extcode4
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setExtcode4(Integer extcode4) {
		this.extcode4 = extcode4;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.extcode5
	 *
	 * @return the value of bsp_orderproducts.extcode5
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Integer getExtcode5() {
		return extcode5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.extcode5
	 *
	 * @param extcode5
	 *            the value for bsp_orderproducts.extcode5
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setExtcode5(Integer extcode5) {
		this.extcode5 = extcode5;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.addtime
	 *
	 * @return the value of bsp_orderproducts.addtime
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.addtime
	 *
	 * @param addtime
	 *            the value for bsp_orderproducts.addtime
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.url
	 *
	 * @return the value of bsp_orderproducts.url
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.url
	 *
	 * @param url
	 *            the value for bsp_orderproducts.url
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.itemtotalmny
	 *
	 * @return the value of bsp_orderproducts.itemtotalmny
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public BigDecimal getItemtotalmny() {
		return itemtotalmny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.itemtotalmny
	 *
	 * @param itemtotalmny
	 *            the value for bsp_orderproducts.itemtotalmny
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setItemtotalmny(BigDecimal itemtotalmny) {
		this.itemtotalmny = itemtotalmny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.shipmny
	 *
	 * @return the value of bsp_orderproducts.shipmny
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public BigDecimal getShipmny() {
		return shipmny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.shipmny
	 *
	 * @param shipmny
	 *            the value for bsp_orderproducts.shipmny
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setShipmny(BigDecimal shipmny) {
		this.shipmny = shipmny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.handmny
	 *
	 * @return the value of bsp_orderproducts.handmny
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public BigDecimal getHandmny() {
		return handmny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.handmny
	 *
	 * @param handmny
	 *            the value for bsp_orderproducts.handmny
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setHandmny(BigDecimal handmny) {
		this.handmny = handmny;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orderproducts.sendBatch
	 *
	 * @return the value of bsp_orderproducts.sendBatch
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public String getSendbatch() {
		return sendbatch;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orderproducts.sendBatch
	 *
	 * @param sendbatch
	 *            the value for bsp_orderproducts.sendBatch
	 *
	 * @mbggenerated Fri Sep 18 14:42:41 CST 2015
	 */
	public void setSendbatch(String sendbatch) {
		this.sendbatch = sendbatch;
	}
}