package com.runlion.shop.entity;

import java.math.BigDecimal;
import java.util.Date;
import java.util.List;

public class BspOrders {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.oid
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Integer oid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.osn
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String osn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.uid
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Integer uid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.orderstate
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Byte orderstate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.productamount
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private BigDecimal productamount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.orderamount
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private BigDecimal orderamount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.surplusmoney
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private BigDecimal surplusmoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.parentid
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Integer parentid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.isreview
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Byte isreview;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.addtime
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Date addtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.shipsn
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String shipsn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.shipsystemname
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String shipsystemname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.shipfriendname
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String shipfriendname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.shiptime
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Date shiptime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.paysn
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String paysn;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.paysystemname
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String paysystemname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.payfriendname
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String payfriendname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.paymode
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Byte paymode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.paytime
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Date paytime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.regionid
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Integer regionid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.consignee
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String consignee;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.mobile
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String mobile;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.phone
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String phone;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.email
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String email;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.zipcode
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String zipcode;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.address
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String address;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.besttime
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Date besttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.handlingCost
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private BigDecimal handlingcost;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.beginDate
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String begindate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.endDate
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String enddate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.factoryAddress
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String factoryaddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.storeAddress
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String storeaddress;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.paystate
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String paystate;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.salerid
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private Integer salerid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.needinv
	 *
	 * @mbggenerated Wed Sep 02 16:52:39 CST 2015
	 */
	private String needinv;

	/**
	 * 订单到期时间
	 */
	private Date expireTime;

	/**
	 * nc生成的订单的编号
	 */
	private String ncordernum;
	/**
	 * nc是否成功保存的状态
	 */
	private String ncstate;

	public String getNeedinv() {
		return needinv;
	}

	public void setNeedinv(String needinv) {
		this.needinv = needinv;
	}

	public Integer getSalerid() {
		return salerid;
	}

	public void setSalerid(Integer salerid) {
		this.salerid = salerid;
	}

	public String getPaystate() {
		return paystate;
	}

	public void setPaystate(String paystate) {
		this.paystate = paystate;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.shipfee
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private BigDecimal shipfee;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.payfee
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private BigDecimal payfee;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.fullcut
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer fullcut;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.discount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private BigDecimal discount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.paycreditcount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer paycreditcount;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.paycreditmoney
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private BigDecimal paycreditmoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.couponmoney
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer couponmoney;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.weight
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private float weight;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.buyerremark
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String buyerremark;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_orders.ip
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String ip;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.oid
	 *
	 * @return the value of bsp_orders.oid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getOid() {
		return oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.oid
	 *
	 * @param oid
	 *            the value for bsp_orders.oid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setOid(Integer oid) {
		this.oid = oid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.osn
	 *
	 * @return the value of bsp_orders.osn
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getOsn() {
		return osn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.osn
	 *
	 * @param osn
	 *            the value for bsp_orders.osn
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setOsn(String osn) {
		this.osn = osn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.uid
	 *
	 * @return the value of bsp_orders.uid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getUid() {
		return uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.uid
	 *
	 * @param uid
	 *            the value for bsp_orders.uid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setUid(Integer uid) {
		this.uid = uid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.orderstate
	 *
	 * @return the value of bsp_orders.orderstate
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Byte getOrderstate() {
		return orderstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.orderstate
	 *
	 * @param orderstate
	 *            the value for bsp_orders.orderstate
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setOrderstate(Byte orderstate) {
		this.orderstate = orderstate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.productamount
	 *
	 * @return the value of bsp_orders.productamount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public BigDecimal getProductamount() {
		return productamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.productamount
	 *
	 * @param productamount
	 *            the value for bsp_orders.productamount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setProductamount(BigDecimal productamount) {
		this.productamount = productamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.orderamount
	 *
	 * @return the value of bsp_orders.orderamount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public BigDecimal getOrderamount() {
		return orderamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.orderamount
	 *
	 * @param orderamount
	 *            the value for bsp_orders.orderamount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setOrderamount(BigDecimal orderamount) {
		this.orderamount = orderamount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.surplusmoney
	 *
	 * @return the value of bsp_orders.surplusmoney
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public BigDecimal getSurplusmoney() {
		return surplusmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.surplusmoney
	 *
	 * @param surplusmoney
	 *            the value for bsp_orders.surplusmoney
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setSurplusmoney(BigDecimal surplusmoney) {
		this.surplusmoney = surplusmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.parentid
	 *
	 * @return the value of bsp_orders.parentid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.parentid
	 *
	 * @param parentid
	 *            the value for bsp_orders.parentid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.isreview
	 *
	 * @return the value of bsp_orders.isreview
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Byte getIsreview() {
		return isreview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.isreview
	 *
	 * @param isreview
	 *            the value for bsp_orders.isreview
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setIsreview(Byte isreview) {
		this.isreview = isreview;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.addtime
	 *
	 * @return the value of bsp_orders.addtime
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.addtime
	 *
	 * @param addtime
	 *            the value for bsp_orders.addtime
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.shipsn
	 *
	 * @return the value of bsp_orders.shipsn
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getShipsn() {
		return shipsn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.shipsn
	 *
	 * @param shipsn
	 *            the value for bsp_orders.shipsn
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setShipsn(String shipsn) {
		this.shipsn = shipsn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.shipsystemname
	 *
	 * @return the value of bsp_orders.shipsystemname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getShipsystemname() {
		return shipsystemname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.shipsystemname
	 *
	 * @param shipsystemname
	 *            the value for bsp_orders.shipsystemname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setShipsystemname(String shipsystemname) {
		this.shipsystemname = shipsystemname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.shipfriendname
	 *
	 * @return the value of bsp_orders.shipfriendname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getShipfriendname() {
		return shipfriendname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.shipfriendname
	 *
	 * @param shipfriendname
	 *            the value for bsp_orders.shipfriendname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setShipfriendname(String shipfriendname) {
		this.shipfriendname = shipfriendname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.shiptime
	 *
	 * @return the value of bsp_orders.shiptime
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Date getShiptime() {
		return shiptime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.shiptime
	 *
	 * @param shiptime
	 *            the value for bsp_orders.shiptime
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setShiptime(Date shiptime) {
		this.shiptime = shiptime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.paysn
	 *
	 * @return the value of bsp_orders.paysn
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getPaysn() {
		return paysn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.paysn
	 *
	 * @param paysn
	 *            the value for bsp_orders.paysn
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPaysn(String paysn) {
		this.paysn = paysn;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.paysystemname
	 *
	 * @return the value of bsp_orders.paysystemname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getPaysystemname() {
		return paysystemname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.paysystemname
	 *
	 * @param paysystemname
	 *            the value for bsp_orders.paysystemname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPaysystemname(String paysystemname) {
		this.paysystemname = paysystemname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.payfriendname
	 *
	 * @return the value of bsp_orders.payfriendname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getPayfriendname() {
		return payfriendname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.payfriendname
	 *
	 * @param payfriendname
	 *            the value for bsp_orders.payfriendname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPayfriendname(String payfriendname) {
		this.payfriendname = payfriendname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.paymode
	 *
	 * @return the value of bsp_orders.paymode
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Byte getPaymode() {
		return paymode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.paymode
	 *
	 * @param paymode
	 *            the value for bsp_orders.paymode
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPaymode(Byte paymode) {
		this.paymode = paymode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.paytime
	 *
	 * @return the value of bsp_orders.paytime
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Date getPaytime() {
		return paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.paytime
	 *
	 * @param paytime
	 *            the value for bsp_orders.paytime
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPaytime(Date paytime) {
		this.paytime = paytime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.regionid
	 *
	 * @return the value of bsp_orders.regionid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getRegionid() {
		return regionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.regionid
	 *
	 * @param regionid
	 *            the value for bsp_orders.regionid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setRegionid(Integer regionid) {
		this.regionid = regionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.consignee
	 *
	 * @return the value of bsp_orders.consignee
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getConsignee() {
		return consignee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.consignee
	 *
	 * @param consignee
	 *            the value for bsp_orders.consignee
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setConsignee(String consignee) {
		this.consignee = consignee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.mobile
	 *
	 * @return the value of bsp_orders.mobile
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getMobile() {
		return mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.mobile
	 *
	 * @param mobile
	 *            the value for bsp_orders.mobile
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.phone
	 *
	 * @return the value of bsp_orders.phone
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.phone
	 *
	 * @param phone
	 *            the value for bsp_orders.phone
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.email
	 *
	 * @return the value of bsp_orders.email
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.email
	 *
	 * @param email
	 *            the value for bsp_orders.email
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.zipcode
	 *
	 * @return the value of bsp_orders.zipcode
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getZipcode() {
		return zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.zipcode
	 *
	 * @param zipcode
	 *            the value for bsp_orders.zipcode
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.address
	 *
	 * @return the value of bsp_orders.address
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getAddress() {
		return address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.address
	 *
	 * @param address
	 *            the value for bsp_orders.address
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setAddress(String address) {
		this.address = address;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.besttime
	 *
	 * @return the value of bsp_orders.besttime
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Date getBesttime() {
		return besttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.besttime
	 *
	 * @param besttime
	 *            the value for bsp_orders.besttime
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setBesttime(Date besttime) {
		this.besttime = besttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.shipfee
	 *
	 * @return the value of bsp_orders.shipfee
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public BigDecimal getShipfee() {
		return shipfee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.shipfee
	 *
	 * @param shipfee
	 *            the value for bsp_orders.shipfee
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setShipfee(BigDecimal shipfee) {
		this.shipfee = shipfee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.payfee
	 *
	 * @return the value of bsp_orders.payfee
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public BigDecimal getPayfee() {
		return payfee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.payfee
	 *
	 * @param payfee
	 *            the value for bsp_orders.payfee
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPayfee(BigDecimal payfee) {
		this.payfee = payfee;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.fullcut
	 *
	 * @return the value of bsp_orders.fullcut
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getFullcut() {
		return fullcut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.fullcut
	 *
	 * @param fullcut
	 *            the value for bsp_orders.fullcut
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setFullcut(Integer fullcut) {
		this.fullcut = fullcut;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.discount
	 *
	 * @return the value of bsp_orders.discount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public BigDecimal getDiscount() {
		return discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.discount
	 *
	 * @param discount
	 *            the value for bsp_orders.discount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setDiscount(BigDecimal discount) {
		this.discount = discount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.paycreditcount
	 *
	 * @return the value of bsp_orders.paycreditcount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getPaycreditcount() {
		return paycreditcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.paycreditcount
	 *
	 * @param paycreditcount
	 *            the value for bsp_orders.paycreditcount
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPaycreditcount(Integer paycreditcount) {
		this.paycreditcount = paycreditcount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.paycreditmoney
	 *
	 * @return the value of bsp_orders.paycreditmoney
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public BigDecimal getPaycreditmoney() {
		return paycreditmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.paycreditmoney
	 *
	 * @param paycreditmoney
	 *            the value for bsp_orders.paycreditmoney
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPaycreditmoney(BigDecimal paycreditmoney) {
		this.paycreditmoney = paycreditmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.couponmoney
	 *
	 * @return the value of bsp_orders.couponmoney
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getCouponmoney() {
		return couponmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.couponmoney
	 *
	 * @param couponmoney
	 *            the value for bsp_orders.couponmoney
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setCouponmoney(Integer couponmoney) {
		this.couponmoney = couponmoney;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.weight
	 *
	 * @return the value of bsp_orders.weight
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public float getWeight() {
		return weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.weight
	 *
	 * @param weight
	 *            the value for bsp_orders.weight
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setWeight(float weight) {
		this.weight = weight;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.buyerremark
	 *
	 * @return the value of bsp_orders.buyerremark
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getBuyerremark() {
		return buyerremark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.buyerremark
	 *
	 * @param buyerremark
	 *            the value for bsp_orders.buyerremark
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setBuyerremark(String buyerremark) {
		this.buyerremark = buyerremark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.ip
	 *
	 * @return the value of bsp_orders.ip
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getIp() {
		return ip;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.ip
	 *
	 * @param ip
	 *            the value for bsp_orders.ip
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setIp(String ip) {
		this.ip = ip;
	}

	public List<BspOrderproducts> boplist;

	private String factoryAddress;

	private String storeAddress;

	public String getStoreAddress() {
		return storeAddress;
	}

	public void setStoreAddress(String storeAddress) {
		this.storeAddress = storeAddress;
	}

	public String getFactoryAddress() {
		return factoryAddress;
	}

	public void setFactoryAddress(String factoryAddress) {
		this.factoryAddress = factoryAddress;
	}

	public List<BspOrderproducts> getBoplist() {
		return boplist;
	}

	public void setBoplist(List<BspOrderproducts> boplist) {
		this.boplist = boplist;
	}

	private Integer userrole;
	private String remark;

	public Integer getUserrole() {
		return userrole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.userrole
	 *
	 * @param userrole
	 *            the value for bsp_orders.userrole
	 *
	 * @mbggenerated Wed Sep 02 16:02:38 CST 2015
	 */
	public void setUserrole(Integer userrole) {
		this.userrole = userrole;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_orders.remark
	 *
	 * @return the value of bsp_orders.remark
	 *
	 * @mbggenerated Wed Sep 02 16:02:38 CST 2015
	 */
	public String getRemark() {
		return remark;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_orders.remark
	 *
	 * @param remark
	 *            the value for bsp_orders.remark
	 *
	 * @mbggenerated Wed Sep 02 16:02:38 CST 2015
	 */
	public void setRemark(String remark) {
		this.remark = remark;
	}

	public BigDecimal getHandlingcost() {
		return handlingcost;
	}

	public void setHandlingcost(BigDecimal handlingcost) {
		this.handlingcost = handlingcost;
	}

	public String getBegindate() {
		return begindate;
	}

	public void setBegindate(String begindate) {
		this.begindate = begindate;
	}

	public String getEnddate() {
		return enddate;
	}

	public void setEnddate(String enddate) {
		this.enddate = enddate;
	}

	public String getFactoryaddress() {
		return factoryaddress;
	}

	public void setFactoryaddress(String factoryaddress) {
		this.factoryaddress = factoryaddress;
	}

	public String getStoreaddress() {
		return storeaddress;
	}

	public void setStoreaddress(String storeaddress) {
		this.storeaddress = storeaddress;
	}

	public Date getExpireTime() {
		return expireTime;
	}

	public void setExpireTime(Date expireTime) {
		this.expireTime = expireTime;
	}

	public String getNcordernum() {
		return ncordernum;
	}

	public void setNcordernum(String ncordernum) {
		this.ncordernum = ncordernum;
	}

	public String getNcstate() {
		return ncstate;
	}

	public void setNcstate(String ncstate) {
		this.ncstate = ncstate;
	}

}