package com.runlion.shop.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BspOrderrefunds {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.refundid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer refundid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.oid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer oid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.osn
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String osn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.uid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.state
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Byte state;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.applytime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Date applytime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.paymoney
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private BigDecimal paymoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.refundmoney
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private BigDecimal refundmoney;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.refundsn
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String refundsn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.refundsystemname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String refundsystemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.refundfriendname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String refundfriendname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.refundtime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Date refundtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.paysn
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String paysn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.paysystemname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String paysystemname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_orderrefunds.payfriendname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String payfriendname;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.refundid
     *
     * @return the value of bsp_orderrefunds.refundid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getRefundid() {
        return refundid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.refundid
     *
     * @param refundid the value for bsp_orderrefunds.refundid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setRefundid(Integer refundid) {
        this.refundid = refundid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.oid
     *
     * @return the value of bsp_orderrefunds.oid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getOid() {
        return oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.oid
     *
     * @param oid the value for bsp_orderrefunds.oid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setOid(Integer oid) {
        this.oid = oid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.osn
     *
     * @return the value of bsp_orderrefunds.osn
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getOsn() {
        return osn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.osn
     *
     * @param osn the value for bsp_orderrefunds.osn
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setOsn(String osn) {
        this.osn = osn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.uid
     *
     * @return the value of bsp_orderrefunds.uid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.uid
     *
     * @param uid the value for bsp_orderrefunds.uid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.state
     *
     * @return the value of bsp_orderrefunds.state
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Byte getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.state
     *
     * @param state the value for bsp_orderrefunds.state
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setState(Byte state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.applytime
     *
     * @return the value of bsp_orderrefunds.applytime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Date getApplytime() {
        return applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.applytime
     *
     * @param applytime the value for bsp_orderrefunds.applytime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setApplytime(Date applytime) {
        this.applytime = applytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.paymoney
     *
     * @return the value of bsp_orderrefunds.paymoney
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public BigDecimal getPaymoney() {
        return paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.paymoney
     *
     * @param paymoney the value for bsp_orderrefunds.paymoney
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setPaymoney(BigDecimal paymoney) {
        this.paymoney = paymoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.refundmoney
     *
     * @return the value of bsp_orderrefunds.refundmoney
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public BigDecimal getRefundmoney() {
        return refundmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.refundmoney
     *
     * @param refundmoney the value for bsp_orderrefunds.refundmoney
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setRefundmoney(BigDecimal refundmoney) {
        this.refundmoney = refundmoney;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.refundsn
     *
     * @return the value of bsp_orderrefunds.refundsn
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getRefundsn() {
        return refundsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.refundsn
     *
     * @param refundsn the value for bsp_orderrefunds.refundsn
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setRefundsn(String refundsn) {
        this.refundsn = refundsn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.refundsystemname
     *
     * @return the value of bsp_orderrefunds.refundsystemname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getRefundsystemname() {
        return refundsystemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.refundsystemname
     *
     * @param refundsystemname the value for bsp_orderrefunds.refundsystemname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setRefundsystemname(String refundsystemname) {
        this.refundsystemname = refundsystemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.refundfriendname
     *
     * @return the value of bsp_orderrefunds.refundfriendname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getRefundfriendname() {
        return refundfriendname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.refundfriendname
     *
     * @param refundfriendname the value for bsp_orderrefunds.refundfriendname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setRefundfriendname(String refundfriendname) {
        this.refundfriendname = refundfriendname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.refundtime
     *
     * @return the value of bsp_orderrefunds.refundtime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Date getRefundtime() {
        return refundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.refundtime
     *
     * @param refundtime the value for bsp_orderrefunds.refundtime
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setRefundtime(Date refundtime) {
        this.refundtime = refundtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.paysn
     *
     * @return the value of bsp_orderrefunds.paysn
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getPaysn() {
        return paysn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.paysn
     *
     * @param paysn the value for bsp_orderrefunds.paysn
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setPaysn(String paysn) {
        this.paysn = paysn;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.paysystemname
     *
     * @return the value of bsp_orderrefunds.paysystemname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getPaysystemname() {
        return paysystemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.paysystemname
     *
     * @param paysystemname the value for bsp_orderrefunds.paysystemname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setPaysystemname(String paysystemname) {
        this.paysystemname = paysystemname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_orderrefunds.payfriendname
     *
     * @return the value of bsp_orderrefunds.payfriendname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getPayfriendname() {
        return payfriendname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_orderrefunds.payfriendname
     *
     * @param payfriendname the value for bsp_orderrefunds.payfriendname
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setPayfriendname(String payfriendname) {
        this.payfriendname = payfriendname;
    }
}