package com.runlion.shop.entity;

import java.math.BigDecimal;
import java.util.Date;

public class BspProductsregionspriceLog {

	public BspProductsregionspriceLog() {

	}

	public BspProductsregionspriceLog(int productregionsid, String pricetype,
			double price, Date planeffecttime) {
		this.addtime = new Date();
		this.productregionsid = productregionsid;
		this.price = BigDecimal.valueOf(price);
		this.pricetype = pricetype;
		this.planeffecttime = planeffecttime;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.id
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.priceId
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private Integer priceid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.productregionsId
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private Integer productregionsid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.price
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private BigDecimal price;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.priceType
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private String pricetype;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.buyminquan
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private Double buyminquan;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.addtime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private Date addtime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.edittime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private Date edittime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.planeffecttime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private Date planeffecttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.effecttime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private Date effecttime;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsprice_log.iseffect
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	private String iseffect;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.id
	 *
	 * @return the value of bsp_productsregionsprice_log.id
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.id
	 *
	 * @param id
	 *            the value for bsp_productsregionsprice_log.id
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.priceId
	 *
	 * @return the value of bsp_productsregionsprice_log.priceId
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public Integer getPriceid() {
		return priceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.priceId
	 *
	 * @param priceid
	 *            the value for bsp_productsregionsprice_log.priceId
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setPriceid(Integer priceid) {
		this.priceid = priceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column
	 * bsp_productsregionsprice_log.productregionsId
	 *
	 * @return the value of bsp_productsregionsprice_log.productregionsId
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public Integer getProductregionsid() {
		return productregionsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column
	 * bsp_productsregionsprice_log.productregionsId
	 *
	 * @param productregionsid
	 *            the value for bsp_productsregionsprice_log.productregionsId
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setProductregionsid(Integer productregionsid) {
		this.productregionsid = productregionsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.price
	 *
	 * @return the value of bsp_productsregionsprice_log.price
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public BigDecimal getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.price
	 *
	 * @param price
	 *            the value for bsp_productsregionsprice_log.price
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setPrice(BigDecimal price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.priceType
	 *
	 * @return the value of bsp_productsregionsprice_log.priceType
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public String getPricetype() {
		return pricetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.priceType
	 *
	 * @param pricetype
	 *            the value for bsp_productsregionsprice_log.priceType
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setPricetype(String pricetype) {
		this.pricetype = pricetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.buyminquan
	 *
	 * @return the value of bsp_productsregionsprice_log.buyminquan
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public Double getBuyminquan() {
		return buyminquan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.buyminquan
	 *
	 * @param buyminquan
	 *            the value for bsp_productsregionsprice_log.buyminquan
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setBuyminquan(Double buyminquan) {
		this.buyminquan = buyminquan;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.addtime
	 *
	 * @return the value of bsp_productsregionsprice_log.addtime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public Date getAddtime() {
		return addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.addtime
	 *
	 * @param addtime
	 *            the value for bsp_productsregionsprice_log.addtime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setAddtime(Date addtime) {
		this.addtime = addtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.edittime
	 *
	 * @return the value of bsp_productsregionsprice_log.edittime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public Date getEdittime() {
		return edittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.edittime
	 *
	 * @param edittime
	 *            the value for bsp_productsregionsprice_log.edittime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setEdittime(Date edittime) {
		this.edittime = edittime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.planeffecttime
	 *
	 * @return the value of bsp_productsregionsprice_log.planeffecttime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public Date getPlaneffecttime() {
		return planeffecttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.planeffecttime
	 *
	 * @param planeffecttime
	 *            the value for bsp_productsregionsprice_log.planeffecttime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setPlaneffecttime(Date planeffecttime) {
		this.planeffecttime = planeffecttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.effecttime
	 *
	 * @return the value of bsp_productsregionsprice_log.effecttime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public Date getEffecttime() {
		return effecttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.effecttime
	 *
	 * @param effecttime
	 *            the value for bsp_productsregionsprice_log.effecttime
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setEffecttime(Date effecttime) {
		this.effecttime = effecttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsprice_log.iseffect
	 *
	 * @return the value of bsp_productsregionsprice_log.iseffect
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public String getIseffect() {
		return iseffect;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsprice_log.iseffect
	 *
	 * @param iseffect
	 *            the value for bsp_productsregionsprice_log.iseffect
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	public void setIseffect(String iseffect) {
		this.iseffect = iseffect;
	}

	public static BspProductsregionspriceLog copyInfo(BspProductsregionsprice p) {
		BspProductsregionspriceLog log = new BspProductsregionspriceLog();
		log.setPriceid(p.getId());
		log.setProductregionsid(p.getProductregionsid());
		log.setPrice(p.getPrice());
		log.setPricetype(p.getPricetype());
		log.setBuyminquan(p.getBuyminquan());
		log.setAddtime(new Date());
		return log;
	}

	public static BspProregionextprice copyExtInfo(BspProductsregionspriceLog p) {
		BspProregionextprice log = new BspProregionextprice();
		log.setId(p.getId());
		log.setProregionid(p.getProductregionsid());
		log.setValue(p.getPrice());
		log.setType(p.getPricetype());
		if (p.getPricetype().equals("21")) {
			log.setType("1");
			log.setName(BspProregionextprice.STORE_PICK_NAME);
		} else if (p.getPricetype().equals("22")) {
			log.setType("2");
			log.setName(BspProregionextprice.FAC_PICK_NAME);
		} else if (p.getPricetype().equals("23")) {
			log.setType("3");
			log.setName(BspProregionextprice.SEND_HOME_NAME);
		}

		return log;
	}

	public static BspProductsregionspriceLog copyInfo(BspProregionextprice p) {
		BspProductsregionspriceLog log = new BspProductsregionspriceLog();
		log.setPriceid(p.getId());
		log.setProductregionsid(p.getProregionid());
		log.setPrice(p.getValue());
		log.setPricetype("2" + p.getType());
		log.setBuyminquan(0.0d);
		log.setAddtime(new Date());
		return log;
	}

	public static BspProductsregionsprice copyInfo(BspProductsregionspriceLog p) {
		BspProductsregionsprice log = new BspProductsregionsprice();
		log.setProductregionsid(p.getProductregionsid());
		log.setPrice(p.getPrice());
		log.setPricetype(p.getPricetype());
		log.setBuyminquan(p.getBuyminquan());
		return log;
	}
}