package com.runlion.shop.entity;

public class BspProductskusRTM implements Comparable<BspProductskusRTM> {

	private String attrvalue = "";// 属性值
	private int isinput = 0;// 是否为输入值
	private String attrname = "";// 属性名称
	private int attrshowtype;// 属性展示类型(0代表文字,1代表图片)
	private String showimg = "";// 商品展示图片

	// 按pid排序
	@Override
	public int compareTo(BspProductskusRTM arg0) {
		return this.getPid().compareTo(arg0.getPid());
	}

	public String getAttrvalue() {
		return attrvalue;
	}

	public void setAttrvalue(String attrvalue) {
		this.attrvalue = attrvalue;
	}

	public int getIsinput() {
		return isinput;
	}

	public void setIsinput(int isinput) {
		this.isinput = isinput;
	}

	public String getAttrname() {
		return attrname;
	}

	public void setAttrname(String attrname) {
		this.attrname = attrname;
	}

	public int getAttrshowtype() {
		return attrshowtype;
	}

	public void setAttrshowtype(int attrshowtype) {
		this.attrshowtype = attrshowtype;
	}

	public String getShowimg() {
		return showimg;
	}

	public void setShowimg(String showimg) {
		this.showimg = showimg;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productskus.recordid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer recordid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productskus.skugid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer skugid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productskus.pid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer pid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productskus.attrid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Short attrid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productskus.attrvalueid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer attrvalueid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productskus.inputvalue
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String inputvalue;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productskus.recordid
	 *
	 * @return the value of bsp_productskus.recordid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getRecordid() {
		return recordid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productskus.recordid
	 *
	 * @param recordid
	 *            the value for bsp_productskus.recordid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setRecordid(Integer recordid) {
		this.recordid = recordid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productskus.skugid
	 *
	 * @return the value of bsp_productskus.skugid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getSkugid() {
		return skugid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productskus.skugid
	 *
	 * @param skugid
	 *            the value for bsp_productskus.skugid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setSkugid(Integer skugid) {
		this.skugid = skugid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productskus.pid
	 *
	 * @return the value of bsp_productskus.pid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getPid() {
		return pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productskus.pid
	 *
	 * @param pid
	 *            the value for bsp_productskus.pid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setPid(Integer pid) {
		this.pid = pid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productskus.attrid
	 *
	 * @return the value of bsp_productskus.attrid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Short getAttrid() {
		return attrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productskus.attrid
	 *
	 * @param attrid
	 *            the value for bsp_productskus.attrid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setAttrid(Short attrid) {
		this.attrid = attrid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productskus.attrvalueid
	 *
	 * @return the value of bsp_productskus.attrvalueid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getAttrvalueid() {
		return attrvalueid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productskus.attrvalueid
	 *
	 * @param attrvalueid
	 *            the value for bsp_productskus.attrvalueid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setAttrvalueid(Integer attrvalueid) {
		this.attrvalueid = attrvalueid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productskus.inputvalue
	 *
	 * @return the value of bsp_productskus.inputvalue
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getInputvalue() {
		return inputvalue;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productskus.inputvalue
	 *
	 * @param inputvalue
	 *            the value for bsp_productskus.inputvalue
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setInputvalue(String inputvalue) {
		this.inputvalue = inputvalue;
	}
}