package com.runlion.shop.entity;

public class BspProductsregionsbrand {

	public BspProductsregionsbrand() {

	}

	public BspProductsregionsbrand(int id, int brandid, int productregionsid) {
		this.id = id;
		this.brandid = brandid;
		this.productregionsid = productregionsid;
	}

	public BspProductsregionsbrand(int brandid, int productregionsid) {
		this.brandid = brandid;
		this.productregionsid = productregionsid;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsbrand.id
	 *
	 * @mbggenerated Fri Aug 07 17:10:39 CST 2015
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsbrand.brandId
	 *
	 * @mbggenerated Fri Aug 07 17:10:39 CST 2015
	 */
	private Integer brandid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregionsbrand.productregionsId
	 *
	 * @mbggenerated Fri Aug 07 17:10:39 CST 2015
	 */
	private Integer productregionsid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsbrand.id
	 *
	 * @return the value of bsp_productsregionsbrand.id
	 *
	 * @mbggenerated Fri Aug 07 17:10:39 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsbrand.id
	 *
	 * @param id
	 *            the value for bsp_productsregionsbrand.id
	 *
	 * @mbggenerated Fri Aug 07 17:10:39 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsbrand.brandId
	 *
	 * @return the value of bsp_productsregionsbrand.brandId
	 *
	 * @mbggenerated Fri Aug 07 17:10:39 CST 2015
	 */
	public Integer getBrandid() {
		return brandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsbrand.brandId
	 *
	 * @param brandid
	 *            the value for bsp_productsregionsbrand.brandId
	 *
	 * @mbggenerated Fri Aug 07 17:10:39 CST 2015
	 */
	public void setBrandid(Integer brandid) {
		this.brandid = brandid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregionsbrand.productregionsId
	 *
	 * @return the value of bsp_productsregionsbrand.productregionsId
	 *
	 * @mbggenerated Fri Aug 07 17:10:39 CST 2015
	 */
	public Integer getProductregionsid() {
		return productregionsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregionsbrand.productregionsId
	 *
	 * @param productregionsid
	 *            the value for bsp_productsregionsbrand.productregionsId
	 *
	 * @mbggenerated Fri Aug 07 17:10:39 CST 2015
	 */
	public void setProductregionsid(Integer productregionsid) {
		this.productregionsid = productregionsid;
	}
}