package com.runlion.shop.entity;

public class BspProductimages {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_productimages.pimgid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer pimgid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_productimages.pid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer pid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_productimages.showimg
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String showimg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_productimages.ismain
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Byte ismain;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_productimages.displayorder
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer displayorder;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_productimages.pimgid
     *
     * @return the value of bsp_productimages.pimgid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getPimgid() {
        return pimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_productimages.pimgid
     *
     * @param pimgid the value for bsp_productimages.pimgid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setPimgid(Integer pimgid) {
        this.pimgid = pimgid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_productimages.pid
     *
     * @return the value of bsp_productimages.pid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_productimages.pid
     *
     * @param pid the value for bsp_productimages.pid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_productimages.showimg
     *
     * @return the value of bsp_productimages.showimg
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getShowimg() {
        return showimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_productimages.showimg
     *
     * @param showimg the value for bsp_productimages.showimg
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setShowimg(String showimg) {
        this.showimg = showimg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_productimages.ismain
     *
     * @return the value of bsp_productimages.ismain
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Byte getIsmain() {
        return ismain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_productimages.ismain
     *
     * @param ismain the value for bsp_productimages.ismain
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setIsmain(Byte ismain) {
        this.ismain = ismain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_productimages.displayorder
     *
     * @return the value of bsp_productimages.displayorder
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getDisplayorder() {
        return displayorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_productimages.displayorder
     *
     * @param displayorder the value for bsp_productimages.displayorder
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setDisplayorder(Integer displayorder) {
        this.displayorder = displayorder;
    }
}