package com.runlion.shop.entity;

import java.math.BigDecimal;

public class BspProductsregions {

	public BspProductsregions() {

	}

	public BspProductsregions(Integer id, Integer productid, Integer regionsid,
			String regionsName) {
		this.id = id;
		this.productid = productid;
		this.regionsid = regionsid;
		this.regionsName = regionsName;

	}

	public BspProductsregions(Integer id, Integer productid, Integer regionsid,
			String regionsName, BigDecimal starthand, BigDecimal startship) {
		this.id = id;
		this.productid = productid;
		this.regionsid = regionsid;
		this.regionsName = regionsName;
		this.starthand = starthand;
		this.startship = startship;
	}

	public BspProductsregions(int productid, int regionsid, String regionsName) {
		this.productid = productid;
		this.regionsid = regionsid;
		this.regionsName = regionsName;
	}

	public BspProductsregions(int productid, int regionsid) {
		this.productid = productid;
		this.regionsid = regionsid;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregions.Id
	 *
	 * @mbggenerated Thu Jul 02 13:19:05 CST 2015
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregions.productId
	 *
	 * @mbggenerated Thu Jul 02 13:19:05 CST 2015
	 */
	private Integer productid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_productsregions.RegionsId
	 *
	 * @mbggenerated Thu Jul 02 13:19:05 CST 2015
	 */
	private Integer regionsid;

	private String regionsName;
	/**
	 * 起步运费
	 */
	private BigDecimal startship;

	/**
	 * 起步装卸费
	 */
	private BigDecimal starthand;

	public String getRegionsName() {
		return regionsName;
	}

	public void setRegionsName(String regionsName) {
		this.regionsName = regionsName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregions.Id
	 *
	 * @return the value of bsp_productsregions.Id
	 *
	 * @mbggenerated Thu Jul 02 13:19:05 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregions.Id
	 *
	 * @param id
	 *            the value for bsp_productsregions.Id
	 *
	 * @mbggenerated Thu Jul 02 13:19:05 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregions.productId
	 *
	 * @return the value of bsp_productsregions.productId
	 *
	 * @mbggenerated Thu Jul 02 13:19:05 CST 2015
	 */
	public Integer getProductid() {
		return productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregions.productId
	 *
	 * @param productid
	 *            the value for bsp_productsregions.productId
	 *
	 * @mbggenerated Thu Jul 02 13:19:05 CST 2015
	 */
	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_productsregions.RegionsId
	 *
	 * @return the value of bsp_productsregions.RegionsId
	 *
	 * @mbggenerated Thu Jul 02 13:19:05 CST 2015
	 */
	public Integer getRegionsid() {
		return regionsid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_productsregions.RegionsId
	 *
	 * @param regionsid
	 *            the value for bsp_productsregions.RegionsId
	 *
	 * @mbggenerated Thu Jul 02 13:19:05 CST 2015
	 */
	public void setRegionsid(Integer regionsid) {
		this.regionsid = regionsid;
	}

	public BigDecimal getStartship() {
		return startship;
	}

	public void setStartship(BigDecimal startship) {
		this.startship = startship;
	}

	public BigDecimal getStarthand() {
		return starthand;
	}

	public void setStarthand(BigDecimal starthand) {
		this.starthand = starthand;
	}
}