package com.runlion.shop.entity;

import java.math.BigDecimal;

public class BspProregionextprice {

	public static final String STORE_PICK_NAME = "门店自提";
	public static final String FAC_PICK_NAME = "工厂自提";
	public static final String SEND_HOME_NAME = "送货上门";
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_proregionextprice.id
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	private Integer id;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_proregionextprice.name
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_proregionextprice.type
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	private String type;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_proregionextprice.value
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	private BigDecimal value;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_proregionextprice.remarks
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	private String remarks;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_proregionextprice.proregionid
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	private Integer proregionid;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_proregionextprice.id
	 *
	 * @return the value of bsp_proregionextprice.id
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_proregionextprice.id
	 *
	 * @param id
	 *            the value for bsp_proregionextprice.id
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_proregionextprice.name
	 *
	 * @return the value of bsp_proregionextprice.name
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_proregionextprice.name
	 *
	 * @param name
	 *            the value for bsp_proregionextprice.name
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_proregionextprice.type
	 *
	 * @return the value of bsp_proregionextprice.type
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public String getType() {
		return type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_proregionextprice.type
	 *
	 * @param type
	 *            the value for bsp_proregionextprice.type
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public void setType(String type) {
		this.type = type;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_proregionextprice.value
	 *
	 * @return the value of bsp_proregionextprice.value
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public BigDecimal getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_proregionextprice.value
	 *
	 * @param value
	 *            the value for bsp_proregionextprice.value
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public void setValue(BigDecimal value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_proregionextprice.remarks
	 *
	 * @return the value of bsp_proregionextprice.remarks
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_proregionextprice.remarks
	 *
	 * @param remarks
	 *            the value for bsp_proregionextprice.remarks
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_proregionextprice.proregionid
	 *
	 * @return the value of bsp_proregionextprice.proregionid
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public Integer getProregionid() {
		return proregionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_proregionextprice.proregionid
	 *
	 * @param proregionid
	 *            the value for bsp_proregionextprice.proregionid
	 *
	 * @mbggenerated Tue Sep 01 14:58:03 CST 2015
	 */
	public void setProregionid(Integer proregionid) {
		this.proregionid = proregionid;
	}
}