package com.runlion.shop.entity;

public class BspRegionpriecedefunits implements Cloneable {

	@Override
	public BspRegionpriecedefunits clone() {
		try {
			return (BspRegionpriecedefunits) super.clone();
		} catch (CloneNotSupportedException e) {
			e.printStackTrace();
		}
		return null;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regionpriecedefunits.keyid
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	private Integer keyid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regionpriecedefunits.unitid
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	private Integer unitid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regionpriecedefunits.unitname
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	private String unitname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regionpriecedefunits.regionpriceid
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	private Integer regionpriceid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regionpriecedefunits.remarks
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	private String remarks;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regionpriecedefunits.pricetype
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	private String pricetype;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regionpriecedefunits.keyid
	 *
	 * @return the value of bsp_regionpriecedefunits.keyid
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public Integer getKeyid() {
		return keyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regionpriecedefunits.keyid
	 *
	 * @param keyid
	 *            the value for bsp_regionpriecedefunits.keyid
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public void setKeyid(Integer keyid) {
		this.keyid = keyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regionpriecedefunits.unitid
	 *
	 * @return the value of bsp_regionpriecedefunits.unitid
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public Integer getUnitid() {
		return unitid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regionpriecedefunits.unitid
	 *
	 * @param unitid
	 *            the value for bsp_regionpriecedefunits.unitid
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public void setUnitid(Integer unitid) {
		this.unitid = unitid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regionpriecedefunits.unitname
	 *
	 * @return the value of bsp_regionpriecedefunits.unitname
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public String getUnitname() {
		return unitname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regionpriecedefunits.unitname
	 *
	 * @param unitname
	 *            the value for bsp_regionpriecedefunits.unitname
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public void setUnitname(String unitname) {
		this.unitname = unitname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regionpriecedefunits.regionpriceid
	 *
	 * @return the value of bsp_regionpriecedefunits.regionpriceid
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public Integer getRegionpriceid() {
		return regionpriceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regionpriecedefunits.regionpriceid
	 *
	 * @param regionpriceid
	 *            the value for bsp_regionpriecedefunits.regionpriceid
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public void setRegionpriceid(Integer regionpriceid) {
		this.regionpriceid = regionpriceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regionpriecedefunits.remarks
	 *
	 * @return the value of bsp_regionpriecedefunits.remarks
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public String getRemarks() {
		return remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regionpriecedefunits.remarks
	 *
	 * @param remarks
	 *            the value for bsp_regionpriecedefunits.remarks
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regionpriecedefunits.pricetype
	 *
	 * @return the value of bsp_regionpriecedefunits.pricetype
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public String getPricetype() {
		return pricetype;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regionpriecedefunits.pricetype
	 *
	 * @param pricetype
	 *            the value for bsp_regionpriecedefunits.pricetype
	 *
	 * @mbggenerated Thu Jul 30 14:30:03 CST 2015
	 */
	public void setPricetype(String pricetype) {
		this.pricetype = pricetype;
	}
}