package com.runlion.shop.entity;

public class BspRegions {

	private String cid;

	public String getCid() {
		return cid;
	}

	public void setCid(String cid) {
		this.cid = cid;
	}

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.regionid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer regionid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.name
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String name;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.spell
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String spell;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.shortspell
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String shortspell;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.displayorder
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer displayorder;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.parentid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer parentid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.layer
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Byte layer;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.provinceid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer provinceid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.provincename
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String provincename;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.cityid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer cityid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.cityname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String cityname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.countyid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer countyid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.countyname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String countyname;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.streetid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private Integer streetid;

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to
	 * the database column bsp_regions.streetname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	private String streetname;

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.regionid
	 *
	 * @return the value of bsp_regions.regionid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getRegionid() {
		return regionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.regionid
	 *
	 * @param regionid
	 *            the value for bsp_regions.regionid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setRegionid(Integer regionid) {
		this.regionid = regionid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.name
	 *
	 * @return the value of bsp_regions.name
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.name
	 *
	 * @param name
	 *            the value for bsp_regions.name
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.spell
	 *
	 * @return the value of bsp_regions.spell
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getSpell() {
		return spell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.spell
	 *
	 * @param spell
	 *            the value for bsp_regions.spell
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setSpell(String spell) {
		this.spell = spell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.shortspell
	 *
	 * @return the value of bsp_regions.shortspell
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getShortspell() {
		return shortspell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.shortspell
	 *
	 * @param shortspell
	 *            the value for bsp_regions.shortspell
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setShortspell(String shortspell) {
		this.shortspell = shortspell;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.displayorder
	 *
	 * @return the value of bsp_regions.displayorder
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getDisplayorder() {
		return displayorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.displayorder
	 *
	 * @param displayorder
	 *            the value for bsp_regions.displayorder
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setDisplayorder(Integer displayorder) {
		this.displayorder = displayorder;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.parentid
	 *
	 * @return the value of bsp_regions.parentid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getParentid() {
		return parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.parentid
	 *
	 * @param parentid
	 *            the value for bsp_regions.parentid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.layer
	 *
	 * @return the value of bsp_regions.layer
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Byte getLayer() {
		return layer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.layer
	 *
	 * @param layer
	 *            the value for bsp_regions.layer
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setLayer(Byte layer) {
		this.layer = layer;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.provinceid
	 *
	 * @return the value of bsp_regions.provinceid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getProvinceid() {
		return provinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.provinceid
	 *
	 * @param provinceid
	 *            the value for bsp_regions.provinceid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setProvinceid(Integer provinceid) {
		this.provinceid = provinceid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.provincename
	 *
	 * @return the value of bsp_regions.provincename
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getProvincename() {
		return provincename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.provincename
	 *
	 * @param provincename
	 *            the value for bsp_regions.provincename
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setProvincename(String provincename) {
		this.provincename = provincename;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.cityid
	 *
	 * @return the value of bsp_regions.cityid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getCityid() {
		return cityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.cityid
	 *
	 * @param cityid
	 *            the value for bsp_regions.cityid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setCityid(Integer cityid) {
		this.cityid = cityid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.cityname
	 *
	 * @return the value of bsp_regions.cityname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getCityname() {
		return cityname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.cityname
	 *
	 * @param cityname
	 *            the value for bsp_regions.cityname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setCityname(String cityname) {
		this.cityname = cityname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.countyid
	 *
	 * @return the value of bsp_regions.countyid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getCountyid() {
		return countyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.countyid
	 *
	 * @param countyid
	 *            the value for bsp_regions.countyid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setCountyid(Integer countyid) {
		this.countyid = countyid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.countyname
	 *
	 * @return the value of bsp_regions.countyname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getCountyname() {
		return countyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.countyname
	 *
	 * @param countyname
	 *            the value for bsp_regions.countyname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setCountyname(String countyname) {
		this.countyname = countyname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.streetid
	 *
	 * @return the value of bsp_regions.streetid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public Integer getStreetid() {
		return streetid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.streetid
	 *
	 * @param streetid
	 *            the value for bsp_regions.streetid
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setStreetid(Integer streetid) {
		this.streetid = streetid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the
	 * value of the database column bsp_regions.streetname
	 *
	 * @return the value of bsp_regions.streetname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public String getStreetname() {
		return streetname;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the
	 * value of the database column bsp_regions.streetname
	 *
	 * @param streetname
	 *            the value for bsp_regions.streetname
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	public void setStreetname(String streetname) {
		this.streetname = streetname;
	}
}