package com.runlion.shop.entity;

public class BspShipaddresses {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.said
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer said;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.uid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.regionid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer regionid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.isdefault
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Byte isdefault;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.alias
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String alias;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.consignee
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String consignee;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.mobile
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String mobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.phone
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.email
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.zipcode
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_shipaddresses.address
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String address;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.said
     *
     * @return the value of bsp_shipaddresses.said
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getSaid() {
        return said;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.said
     *
     * @param said the value for bsp_shipaddresses.said
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setSaid(Integer said) {
        this.said = said;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.uid
     *
     * @return the value of bsp_shipaddresses.uid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.uid
     *
     * @param uid the value for bsp_shipaddresses.uid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.regionid
     *
     * @return the value of bsp_shipaddresses.regionid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getRegionid() {
        return regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.regionid
     *
     * @param regionid the value for bsp_shipaddresses.regionid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setRegionid(Integer regionid) {
        this.regionid = regionid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.isdefault
     *
     * @return the value of bsp_shipaddresses.isdefault
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Byte getIsdefault() {
        return isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.isdefault
     *
     * @param isdefault the value for bsp_shipaddresses.isdefault
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setIsdefault(Byte isdefault) {
        this.isdefault = isdefault;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.alias
     *
     * @return the value of bsp_shipaddresses.alias
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getAlias() {
        return alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.alias
     *
     * @param alias the value for bsp_shipaddresses.alias
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setAlias(String alias) {
        this.alias = alias;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.consignee
     *
     * @return the value of bsp_shipaddresses.consignee
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.consignee
     *
     * @param consignee the value for bsp_shipaddresses.consignee
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.mobile
     *
     * @return the value of bsp_shipaddresses.mobile
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.mobile
     *
     * @param mobile the value for bsp_shipaddresses.mobile
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.phone
     *
     * @return the value of bsp_shipaddresses.phone
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.phone
     *
     * @param phone the value for bsp_shipaddresses.phone
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setPhone(String phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.email
     *
     * @return the value of bsp_shipaddresses.email
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.email
     *
     * @param email the value for bsp_shipaddresses.email
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setEmail(String email) {
        this.email = email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.zipcode
     *
     * @return the value of bsp_shipaddresses.zipcode
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.zipcode
     *
     * @param zipcode the value for bsp_shipaddresses.zipcode
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_shipaddresses.address
     *
     * @return the value of bsp_shipaddresses.address
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_shipaddresses.address
     *
     * @param address the value for bsp_shipaddresses.address
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setAddress(String address) {
        this.address = address;
    }
    
    private BspRegions regions;

	public BspRegions getRegions() {
		return regions;
	}

	public void setRegions(BspRegions regions) {
		this.regions = regions;
	}
    
}