package com.runlion.shop.entity;

import java.util.Date;

public class BspUsercarinfor {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.id
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.userid
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.carnum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private String carnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.motornum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private String motornum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.mobilenum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private String mobilenum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.telnum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private String telnum;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.zipcode
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private String zipcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.remarks
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private String remarks;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.lastusetime
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private Date lastusetime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.lastuptime
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private Date lastuptime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_usercarinfor.userroleid
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    private Integer userroleid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.id
     *
     * @return the value of bsp_usercarinfor.id
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.id
     *
     * @param id the value for bsp_usercarinfor.id
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.userid
     *
     * @return the value of bsp_usercarinfor.userid
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.userid
     *
     * @param userid the value for bsp_usercarinfor.userid
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.carnum
     *
     * @return the value of bsp_usercarinfor.carnum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public String getCarnum() {
        return carnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.carnum
     *
     * @param carnum the value for bsp_usercarinfor.carnum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setCarnum(String carnum) {
        this.carnum = carnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.motornum
     *
     * @return the value of bsp_usercarinfor.motornum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public String getMotornum() {
        return motornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.motornum
     *
     * @param motornum the value for bsp_usercarinfor.motornum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setMotornum(String motornum) {
        this.motornum = motornum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.mobilenum
     *
     * @return the value of bsp_usercarinfor.mobilenum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public String getMobilenum() {
        return mobilenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.mobilenum
     *
     * @param mobilenum the value for bsp_usercarinfor.mobilenum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setMobilenum(String mobilenum) {
        this.mobilenum = mobilenum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.telnum
     *
     * @return the value of bsp_usercarinfor.telnum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public String getTelnum() {
        return telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.telnum
     *
     * @param telnum the value for bsp_usercarinfor.telnum
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setTelnum(String telnum) {
        this.telnum = telnum;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.zipcode
     *
     * @return the value of bsp_usercarinfor.zipcode
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public String getZipcode() {
        return zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.zipcode
     *
     * @param zipcode the value for bsp_usercarinfor.zipcode
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setZipcode(String zipcode) {
        this.zipcode = zipcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.remarks
     *
     * @return the value of bsp_usercarinfor.remarks
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public String getRemarks() {
        return remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.remarks
     *
     * @param remarks the value for bsp_usercarinfor.remarks
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.lastusetime
     *
     * @return the value of bsp_usercarinfor.lastusetime
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public Date getLastusetime() {
        return lastusetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.lastusetime
     *
     * @param lastusetime the value for bsp_usercarinfor.lastusetime
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setLastusetime(Date lastusetime) {
        this.lastusetime = lastusetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.lastuptime
     *
     * @return the value of bsp_usercarinfor.lastuptime
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public Date getLastuptime() {
        return lastuptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.lastuptime
     *
     * @param lastuptime the value for bsp_usercarinfor.lastuptime
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setLastuptime(Date lastuptime) {
        this.lastuptime = lastuptime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_usercarinfor.userroleid
     *
     * @return the value of bsp_usercarinfor.userroleid
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public Integer getUserroleid() {
        return userroleid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_usercarinfor.userroleid
     *
     * @param userroleid the value for bsp_usercarinfor.userroleid
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    public void setUserroleid(Integer userroleid) {
        this.userroleid = userroleid;
    }
}