package com.runlion.shop.entity;

import java.util.ArrayList;
import java.util.List;

public class BspUserranksExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public BspUserranksExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserridIsNull() {
            addCriterion("userrid is null");
            return (Criteria) this;
        }

        public Criteria andUserridIsNotNull() {
            addCriterion("userrid is not null");
            return (Criteria) this;
        }

        public Criteria andUserridEqualTo(Short value) {
            addCriterion("userrid =", value, "userrid");
            return (Criteria) this;
        }

        public Criteria andUserridNotEqualTo(Short value) {
            addCriterion("userrid <>", value, "userrid");
            return (Criteria) this;
        }

        public Criteria andUserridGreaterThan(Short value) {
            addCriterion("userrid >", value, "userrid");
            return (Criteria) this;
        }

        public Criteria andUserridGreaterThanOrEqualTo(Short value) {
            addCriterion("userrid >=", value, "userrid");
            return (Criteria) this;
        }

        public Criteria andUserridLessThan(Short value) {
            addCriterion("userrid <", value, "userrid");
            return (Criteria) this;
        }

        public Criteria andUserridLessThanOrEqualTo(Short value) {
            addCriterion("userrid <=", value, "userrid");
            return (Criteria) this;
        }

        public Criteria andUserridIn(List<Short> values) {
            addCriterion("userrid in", values, "userrid");
            return (Criteria) this;
        }

        public Criteria andUserridNotIn(List<Short> values) {
            addCriterion("userrid not in", values, "userrid");
            return (Criteria) this;
        }

        public Criteria andUserridBetween(Short value1, Short value2) {
            addCriterion("userrid between", value1, value2, "userrid");
            return (Criteria) this;
        }

        public Criteria andUserridNotBetween(Short value1, Short value2) {
            addCriterion("userrid not between", value1, value2, "userrid");
            return (Criteria) this;
        }

        public Criteria andSystemIsNull() {
            addCriterion("system is null");
            return (Criteria) this;
        }

        public Criteria andSystemIsNotNull() {
            addCriterion("system is not null");
            return (Criteria) this;
        }

        public Criteria andSystemEqualTo(Integer value) {
            addCriterion("system =", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotEqualTo(Integer value) {
            addCriterion("system <>", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThan(Integer value) {
            addCriterion("system >", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemGreaterThanOrEqualTo(Integer value) {
            addCriterion("system >=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThan(Integer value) {
            addCriterion("system <", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemLessThanOrEqualTo(Integer value) {
            addCriterion("system <=", value, "system");
            return (Criteria) this;
        }

        public Criteria andSystemIn(List<Integer> values) {
            addCriterion("system in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotIn(List<Integer> values) {
            addCriterion("system not in", values, "system");
            return (Criteria) this;
        }

        public Criteria andSystemBetween(Integer value1, Integer value2) {
            addCriterion("system between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andSystemNotBetween(Integer value1, Integer value2) {
            addCriterion("system not between", value1, value2, "system");
            return (Criteria) this;
        }

        public Criteria andTitleIsNull() {
            addCriterion("title is null");
            return (Criteria) this;
        }

        public Criteria andTitleIsNotNull() {
            addCriterion("title is not null");
            return (Criteria) this;
        }

        public Criteria andTitleEqualTo(String value) {
            addCriterion("title =", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotEqualTo(String value) {
            addCriterion("title <>", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThan(String value) {
            addCriterion("title >", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleGreaterThanOrEqualTo(String value) {
            addCriterion("title >=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThan(String value) {
            addCriterion("title <", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLessThanOrEqualTo(String value) {
            addCriterion("title <=", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleLike(String value) {
            addCriterion("title like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotLike(String value) {
            addCriterion("title not like", value, "title");
            return (Criteria) this;
        }

        public Criteria andTitleIn(List<String> values) {
            addCriterion("title in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotIn(List<String> values) {
            addCriterion("title not in", values, "title");
            return (Criteria) this;
        }

        public Criteria andTitleBetween(String value1, String value2) {
            addCriterion("title between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andTitleNotBetween(String value1, String value2) {
            addCriterion("title not between", value1, value2, "title");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNull() {
            addCriterion("avatar is null");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNotNull() {
            addCriterion("avatar is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarEqualTo(String value) {
            addCriterion("avatar =", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotEqualTo(String value) {
            addCriterion("avatar <>", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThan(String value) {
            addCriterion("avatar >", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("avatar >=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThan(String value) {
            addCriterion("avatar <", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThanOrEqualTo(String value) {
            addCriterion("avatar <=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLike(String value) {
            addCriterion("avatar like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotLike(String value) {
            addCriterion("avatar not like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarIn(List<String> values) {
            addCriterion("avatar in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotIn(List<String> values) {
            addCriterion("avatar not in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarBetween(String value1, String value2) {
            addCriterion("avatar between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotBetween(String value1, String value2) {
            addCriterion("avatar not between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andCreditslowerIsNull() {
            addCriterion("creditslower is null");
            return (Criteria) this;
        }

        public Criteria andCreditslowerIsNotNull() {
            addCriterion("creditslower is not null");
            return (Criteria) this;
        }

        public Criteria andCreditslowerEqualTo(Integer value) {
            addCriterion("creditslower =", value, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditslowerNotEqualTo(Integer value) {
            addCriterion("creditslower <>", value, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditslowerGreaterThan(Integer value) {
            addCriterion("creditslower >", value, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditslowerGreaterThanOrEqualTo(Integer value) {
            addCriterion("creditslower >=", value, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditslowerLessThan(Integer value) {
            addCriterion("creditslower <", value, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditslowerLessThanOrEqualTo(Integer value) {
            addCriterion("creditslower <=", value, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditslowerIn(List<Integer> values) {
            addCriterion("creditslower in", values, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditslowerNotIn(List<Integer> values) {
            addCriterion("creditslower not in", values, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditslowerBetween(Integer value1, Integer value2) {
            addCriterion("creditslower between", value1, value2, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditslowerNotBetween(Integer value1, Integer value2) {
            addCriterion("creditslower not between", value1, value2, "creditslower");
            return (Criteria) this;
        }

        public Criteria andCreditsupperIsNull() {
            addCriterion("creditsupper is null");
            return (Criteria) this;
        }

        public Criteria andCreditsupperIsNotNull() {
            addCriterion("creditsupper is not null");
            return (Criteria) this;
        }

        public Criteria andCreditsupperEqualTo(Integer value) {
            addCriterion("creditsupper =", value, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andCreditsupperNotEqualTo(Integer value) {
            addCriterion("creditsupper <>", value, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andCreditsupperGreaterThan(Integer value) {
            addCriterion("creditsupper >", value, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andCreditsupperGreaterThanOrEqualTo(Integer value) {
            addCriterion("creditsupper >=", value, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andCreditsupperLessThan(Integer value) {
            addCriterion("creditsupper <", value, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andCreditsupperLessThanOrEqualTo(Integer value) {
            addCriterion("creditsupper <=", value, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andCreditsupperIn(List<Integer> values) {
            addCriterion("creditsupper in", values, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andCreditsupperNotIn(List<Integer> values) {
            addCriterion("creditsupper not in", values, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andCreditsupperBetween(Integer value1, Integer value2) {
            addCriterion("creditsupper between", value1, value2, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andCreditsupperNotBetween(Integer value1, Integer value2) {
            addCriterion("creditsupper not between", value1, value2, "creditsupper");
            return (Criteria) this;
        }

        public Criteria andLimitdaysIsNull() {
            addCriterion("limitdays is null");
            return (Criteria) this;
        }

        public Criteria andLimitdaysIsNotNull() {
            addCriterion("limitdays is not null");
            return (Criteria) this;
        }

        public Criteria andLimitdaysEqualTo(Integer value) {
            addCriterion("limitdays =", value, "limitdays");
            return (Criteria) this;
        }

        public Criteria andLimitdaysNotEqualTo(Integer value) {
            addCriterion("limitdays <>", value, "limitdays");
            return (Criteria) this;
        }

        public Criteria andLimitdaysGreaterThan(Integer value) {
            addCriterion("limitdays >", value, "limitdays");
            return (Criteria) this;
        }

        public Criteria andLimitdaysGreaterThanOrEqualTo(Integer value) {
            addCriterion("limitdays >=", value, "limitdays");
            return (Criteria) this;
        }

        public Criteria andLimitdaysLessThan(Integer value) {
            addCriterion("limitdays <", value, "limitdays");
            return (Criteria) this;
        }

        public Criteria andLimitdaysLessThanOrEqualTo(Integer value) {
            addCriterion("limitdays <=", value, "limitdays");
            return (Criteria) this;
        }

        public Criteria andLimitdaysIn(List<Integer> values) {
            addCriterion("limitdays in", values, "limitdays");
            return (Criteria) this;
        }

        public Criteria andLimitdaysNotIn(List<Integer> values) {
            addCriterion("limitdays not in", values, "limitdays");
            return (Criteria) this;
        }

        public Criteria andLimitdaysBetween(Integer value1, Integer value2) {
            addCriterion("limitdays between", value1, value2, "limitdays");
            return (Criteria) this;
        }

        public Criteria andLimitdaysNotBetween(Integer value1, Integer value2) {
            addCriterion("limitdays not between", value1, value2, "limitdays");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_userranks
     *
     * @mbggenerated do_not_delete_during_merge Fri Jun 26 14:56:27 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_userranks
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}