package com.runlion.shop.entity;

public class BspUserranks {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_userranks.userrid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Short userrid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_userranks.system
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer system;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_userranks.title
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String title;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_userranks.avatar
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private String avatar;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_userranks.creditslower
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer creditslower;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_userranks.creditsupper
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer creditsupper;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bsp_userranks.limitdays
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    private Integer limitdays;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_userranks.userrid
     *
     * @return the value of bsp_userranks.userrid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Short getUserrid() {
        return userrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_userranks.userrid
     *
     * @param userrid the value for bsp_userranks.userrid
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setUserrid(Short userrid) {
        this.userrid = userrid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_userranks.system
     *
     * @return the value of bsp_userranks.system
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getSystem() {
        return system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_userranks.system
     *
     * @param system the value for bsp_userranks.system
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setSystem(Integer system) {
        this.system = system;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_userranks.title
     *
     * @return the value of bsp_userranks.title
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getTitle() {
        return title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_userranks.title
     *
     * @param title the value for bsp_userranks.title
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setTitle(String title) {
        this.title = title;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_userranks.avatar
     *
     * @return the value of bsp_userranks.avatar
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public String getAvatar() {
        return avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_userranks.avatar
     *
     * @param avatar the value for bsp_userranks.avatar
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setAvatar(String avatar) {
        this.avatar = avatar;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_userranks.creditslower
     *
     * @return the value of bsp_userranks.creditslower
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getCreditslower() {
        return creditslower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_userranks.creditslower
     *
     * @param creditslower the value for bsp_userranks.creditslower
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setCreditslower(Integer creditslower) {
        this.creditslower = creditslower;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_userranks.creditsupper
     *
     * @return the value of bsp_userranks.creditsupper
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getCreditsupper() {
        return creditsupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_userranks.creditsupper
     *
     * @param creditsupper the value for bsp_userranks.creditsupper
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setCreditsupper(Integer creditsupper) {
        this.creditsupper = creditsupper;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bsp_userranks.limitdays
     *
     * @return the value of bsp_userranks.limitdays
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public Integer getLimitdays() {
        return limitdays;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bsp_userranks.limitdays
     *
     * @param limitdays the value for bsp_userranks.limitdays
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    public void setLimitdays(Integer limitdays) {
        this.limitdays = limitdays;
    }
}