package com.runlion.shop.entity;

import java.util.ArrayList;
import java.util.List;

public class BspUnitExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public BspUnitExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUnitidIsNull() {
            addCriterion("unitid is null");
            return (Criteria) this;
        }

        public Criteria andUnitidIsNotNull() {
            addCriterion("unitid is not null");
            return (Criteria) this;
        }

        public Criteria andUnitidEqualTo(Integer value) {
            addCriterion("unitid =", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotEqualTo(Integer value) {
            addCriterion("unitid <>", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidGreaterThan(Integer value) {
            addCriterion("unitid >", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidGreaterThanOrEqualTo(Integer value) {
            addCriterion("unitid >=", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidLessThan(Integer value) {
            addCriterion("unitid <", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidLessThanOrEqualTo(Integer value) {
            addCriterion("unitid <=", value, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidIn(List<Integer> values) {
            addCriterion("unitid in", values, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotIn(List<Integer> values) {
            addCriterion("unitid not in", values, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidBetween(Integer value1, Integer value2) {
            addCriterion("unitid between", value1, value2, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitidNotBetween(Integer value1, Integer value2) {
            addCriterion("unitid not between", value1, value2, "unitid");
            return (Criteria) this;
        }

        public Criteria andUnitnameIsNull() {
            addCriterion("unitname is null");
            return (Criteria) this;
        }

        public Criteria andUnitnameIsNotNull() {
            addCriterion("unitname is not null");
            return (Criteria) this;
        }

        public Criteria andUnitnameEqualTo(String value) {
            addCriterion("unitname =", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotEqualTo(String value) {
            addCriterion("unitname <>", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameGreaterThan(String value) {
            addCriterion("unitname >", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameGreaterThanOrEqualTo(String value) {
            addCriterion("unitname >=", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLessThan(String value) {
            addCriterion("unitname <", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLessThanOrEqualTo(String value) {
            addCriterion("unitname <=", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameLike(String value) {
            addCriterion("unitname like", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotLike(String value) {
            addCriterion("unitname not like", value, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameIn(List<String> values) {
            addCriterion("unitname in", values, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotIn(List<String> values) {
            addCriterion("unitname not in", values, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameBetween(String value1, String value2) {
            addCriterion("unitname between", value1, value2, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitnameNotBetween(String value1, String value2) {
            addCriterion("unitname not between", value1, value2, "unitname");
            return (Criteria) this;
        }

        public Criteria andUnitennameIsNull() {
            addCriterion("unitenname is null");
            return (Criteria) this;
        }

        public Criteria andUnitennameIsNotNull() {
            addCriterion("unitenname is not null");
            return (Criteria) this;
        }

        public Criteria andUnitennameEqualTo(String value) {
            addCriterion("unitenname =", value, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameNotEqualTo(String value) {
            addCriterion("unitenname <>", value, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameGreaterThan(String value) {
            addCriterion("unitenname >", value, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameGreaterThanOrEqualTo(String value) {
            addCriterion("unitenname >=", value, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameLessThan(String value) {
            addCriterion("unitenname <", value, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameLessThanOrEqualTo(String value) {
            addCriterion("unitenname <=", value, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameLike(String value) {
            addCriterion("unitenname like", value, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameNotLike(String value) {
            addCriterion("unitenname not like", value, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameIn(List<String> values) {
            addCriterion("unitenname in", values, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameNotIn(List<String> values) {
            addCriterion("unitenname not in", values, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameBetween(String value1, String value2) {
            addCriterion("unitenname between", value1, value2, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitennameNotBetween(String value1, String value2) {
            addCriterion("unitenname not between", value1, value2, "unitenname");
            return (Criteria) this;
        }

        public Criteria andUnitshortIsNull() {
            addCriterion("unitshort is null");
            return (Criteria) this;
        }

        public Criteria andUnitshortIsNotNull() {
            addCriterion("unitshort is not null");
            return (Criteria) this;
        }

        public Criteria andUnitshortEqualTo(String value) {
            addCriterion("unitshort =", value, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortNotEqualTo(String value) {
            addCriterion("unitshort <>", value, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortGreaterThan(String value) {
            addCriterion("unitshort >", value, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortGreaterThanOrEqualTo(String value) {
            addCriterion("unitshort >=", value, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortLessThan(String value) {
            addCriterion("unitshort <", value, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortLessThanOrEqualTo(String value) {
            addCriterion("unitshort <=", value, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortLike(String value) {
            addCriterion("unitshort like", value, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortNotLike(String value) {
            addCriterion("unitshort not like", value, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortIn(List<String> values) {
            addCriterion("unitshort in", values, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortNotIn(List<String> values) {
            addCriterion("unitshort not in", values, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortBetween(String value1, String value2) {
            addCriterion("unitshort between", value1, value2, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitshortNotBetween(String value1, String value2) {
            addCriterion("unitshort not between", value1, value2, "unitshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortIsNull() {
            addCriterion("unitenshort is null");
            return (Criteria) this;
        }

        public Criteria andUnitenshortIsNotNull() {
            addCriterion("unitenshort is not null");
            return (Criteria) this;
        }

        public Criteria andUnitenshortEqualTo(String value) {
            addCriterion("unitenshort =", value, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortNotEqualTo(String value) {
            addCriterion("unitenshort <>", value, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortGreaterThan(String value) {
            addCriterion("unitenshort >", value, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortGreaterThanOrEqualTo(String value) {
            addCriterion("unitenshort >=", value, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortLessThan(String value) {
            addCriterion("unitenshort <", value, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortLessThanOrEqualTo(String value) {
            addCriterion("unitenshort <=", value, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortLike(String value) {
            addCriterion("unitenshort like", value, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortNotLike(String value) {
            addCriterion("unitenshort not like", value, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortIn(List<String> values) {
            addCriterion("unitenshort in", values, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortNotIn(List<String> values) {
            addCriterion("unitenshort not in", values, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortBetween(String value1, String value2) {
            addCriterion("unitenshort between", value1, value2, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andUnitenshortNotBetween(String value1, String value2) {
            addCriterion("unitenshort not between", value1, value2, "unitenshort");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNull() {
            addCriterion("remarks is null");
            return (Criteria) this;
        }

        public Criteria andRemarksIsNotNull() {
            addCriterion("remarks is not null");
            return (Criteria) this;
        }

        public Criteria andRemarksEqualTo(String value) {
            addCriterion("remarks =", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotEqualTo(String value) {
            addCriterion("remarks <>", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThan(String value) {
            addCriterion("remarks >", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksGreaterThanOrEqualTo(String value) {
            addCriterion("remarks >=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThan(String value) {
            addCriterion("remarks <", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLessThanOrEqualTo(String value) {
            addCriterion("remarks <=", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksLike(String value) {
            addCriterion("remarks like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotLike(String value) {
            addCriterion("remarks not like", value, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksIn(List<String> values) {
            addCriterion("remarks in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotIn(List<String> values) {
            addCriterion("remarks not in", values, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksBetween(String value1, String value2) {
            addCriterion("remarks between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andRemarksNotBetween(String value1, String value2) {
            addCriterion("remarks not between", value1, value2, "remarks");
            return (Criteria) this;
        }

        public Criteria andUnittypeIsNull() {
            addCriterion("unittype is null");
            return (Criteria) this;
        }

        public Criteria andUnittypeIsNotNull() {
            addCriterion("unittype is not null");
            return (Criteria) this;
        }

        public Criteria andUnittypeEqualTo(Integer value) {
            addCriterion("unittype =", value, "unittype");
            return (Criteria) this;
        }

        public Criteria andUnittypeNotEqualTo(Integer value) {
            addCriterion("unittype <>", value, "unittype");
            return (Criteria) this;
        }

        public Criteria andUnittypeGreaterThan(Integer value) {
            addCriterion("unittype >", value, "unittype");
            return (Criteria) this;
        }

        public Criteria andUnittypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("unittype >=", value, "unittype");
            return (Criteria) this;
        }

        public Criteria andUnittypeLessThan(Integer value) {
            addCriterion("unittype <", value, "unittype");
            return (Criteria) this;
        }

        public Criteria andUnittypeLessThanOrEqualTo(Integer value) {
            addCriterion("unittype <=", value, "unittype");
            return (Criteria) this;
        }

        public Criteria andUnittypeIn(List<Integer> values) {
            addCriterion("unittype in", values, "unittype");
            return (Criteria) this;
        }

        public Criteria andUnittypeNotIn(List<Integer> values) {
            addCriterion("unittype not in", values, "unittype");
            return (Criteria) this;
        }

        public Criteria andUnittypeBetween(Integer value1, Integer value2) {
            addCriterion("unittype between", value1, value2, "unittype");
            return (Criteria) this;
        }

        public Criteria andUnittypeNotBetween(Integer value1, Integer value2) {
            addCriterion("unittype not between", value1, value2, "unittype");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_unit
     *
     * @mbggenerated do_not_delete_during_merge Fri Jul 17 15:13:04 CST 2015
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table bsp_unit
     *
     * @mbggenerated Fri Jul 17 15:13:04 CST 2015
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}