package com.runlion.shop.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspAttributevalues;
import com.runlion.shop.entity.BspAttributevaluesExample;

public interface BspAttributevaluesMapper {

	public int countNewstype(Map<String, Object> par);

	public List<Map<String, Object>> selectNewstypeLimit(Map<String, Object> par);

	List<BspAttributevalues> getFactoryListByAreaId(int id);

	List<BspAttributevalues> getFactoryListByBrand(
			@Param(value = "RegionsId") Integer RegionsId,
			@Param(value = "brandId") Integer brandId);

	List<BspAttributevalues> getBrandListByAreaId(int id);

	List<BspAttributevalues> getProductAttrByID(int id);

	List<BspAttributevalues> getProductPZ();

	List<BspAttributevalues> getProductQD();

	List<BspAttributevalues> getProductPSFS();

	List<BspAttributevalues> getProductSCCJ();

	List<BspAttributevalues> getProductBZ();

	List<BspAttributevalues> getProductPP();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int countByExample(BspAttributevaluesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByExample(BspAttributevaluesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByPrimaryKey(Integer attrvalueid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insert(BspAttributevalues record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insertSelective(BspAttributevalues record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	List<BspAttributevalues> selectByExample(BspAttributevaluesExample example);

	List<BspAttributevalues> selectByAttrid(Short attrid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	BspAttributevalues selectByPrimaryKey(Integer attrvalueid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BspAttributevalues record,
			@Param("example") BspAttributevaluesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExample(@Param("record") BspAttributevalues record,
			@Param("example") BspAttributevaluesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKeySelective(BspAttributevalues record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_attributevalues
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKey(BspAttributevalues record);
}