package com.runlion.shop.dao;

import com.runlion.shop.entity.BspCancelorderReason;
import com.runlion.shop.entity.BspCancelorderReasonExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BspCancelorderReasonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int countByExample(BspCancelorderReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int deleteByExample(BspCancelorderReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int insert(BspCancelorderReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int insertSelective(BspCancelorderReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    List<BspCancelorderReason> selectByExampleWithBLOBs(BspCancelorderReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    List<BspCancelorderReason> selectByExample(BspCancelorderReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    BspCancelorderReason selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspCancelorderReason record, @Param("example") BspCancelorderReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") BspCancelorderReason record, @Param("example") BspCancelorderReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int updateByExample(@Param("record") BspCancelorderReason record, @Param("example") BspCancelorderReasonExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int updateByPrimaryKeySelective(BspCancelorderReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(BspCancelorderReason record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_cancelOrder_reason
     *
     * @mbggenerated Fri Sep 18 11:01:09 CST 2015
     */
    int updateByPrimaryKey(BspCancelorderReason record);
}