package com.runlion.shop.dao;

import com.runlion.shop.entity.BspCreditlogs;
import com.runlion.shop.entity.BspCreditlogsExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface BspCreditlogsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int countByExample(BspCreditlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int deleteByExample(BspCreditlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int deleteByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int insert(BspCreditlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int insertSelective(BspCreditlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    List<BspCreditlogs> selectByExampleWithBLOBs(BspCreditlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    List<BspCreditlogs> selectByExample(BspCreditlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    BspCreditlogs selectByPrimaryKey(Integer logid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspCreditlogs record, @Param("example") BspCreditlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") BspCreditlogs record, @Param("example") BspCreditlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int updateByExample(@Param("record") BspCreditlogs record, @Param("example") BspCreditlogsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int updateByPrimaryKeySelective(BspCreditlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(BspCreditlogs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_creditlogs
     *
     * @mbggenerated Thu Jul 02 09:43:54 CST 2015
     */
    int updateByPrimaryKey(BspCreditlogs record);
    
    List<Map<String,Object>> selectCreditlogsPage(Map<String,Object> map);
}