package com.runlion.shop.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspNews;
import com.runlion.shop.entity.BspNewsExample;

public interface BspNewsMapper {

	public List<Map<String, Object>> selectNewsByType(Map<String, Object> par);

	public void deleteNewsById(Map<String, Object> par);

	public void updateNewsById(Map<String, Object> par);

	public Map<String, Object> selectNewsById(Map<String, Object> par);

	public void insertNews(Map<String, Object> par);

	public int countNews(Map<String, Object> par);

	public List<Map<String, Object>> selectNewsLimit(Map<String, Object> par);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int countByExample(BspNewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByExample(BspNewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByPrimaryKey(Integer newsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insert(BspNews record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insertSelective(BspNews record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	List<BspNews> selectByExampleWithBLOBs(BspNewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	List<BspNews> selectByExample(BspNewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	BspNews selectByPrimaryKey(Integer newsid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BspNews record,
			@Param("example") BspNewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") BspNews record,
			@Param("example") BspNewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExample(@Param("record") BspNews record,
			@Param("example") BspNewsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKeySelective(BspNews record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(BspNews record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_news
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKey(BspNews record);
}