package com.runlion.shop.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspNewstypes;
import com.runlion.shop.entity.BspNewstypesExample;

public interface BspNewstypesMapper {

	public void deleteNewstypeById(Map<String, Object> par);

	public void updateNewstypeById(Map<String, Object> par);

	public Map<String, Object> selectNewstypeById(Map<String, Object> par);

	public void insertNewstype(Map<String, Object> par);

	public int countNewstype(Map<String, Object> par);

	public List<Map<String, Object>> selectNewstypeLimit(Map<String, Object> par);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	int countByExample(BspNewstypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	int deleteByExample(BspNewstypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	int deleteByPrimaryKey(Short newstypeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	int insert(BspNewstypes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	int insertSelective(BspNewstypes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	List<BspNewstypes> selectByExample(BspNewstypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	BspNewstypes selectByPrimaryKey(Integer newstypeid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BspNewstypes record,
			@Param("example") BspNewstypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	int updateByExample(@Param("record") BspNewstypes record,
			@Param("example") BspNewstypesExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	int updateByPrimaryKeySelective(BspNewstypes record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_newstypes
	 *
	 * @mbggenerated Tue Jun 30 15:37:16 CST 2015
	 */
	int updateByPrimaryKey(BspNewstypes record);
}