package com.runlion.shop.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspOrders;
import com.runlion.shop.entity.BspOrdersExample;
import com.runlion.shop.entity.BspProductattributes;
import com.runlion.shop.vo.CartSnapVO;
import com.runlion.shop.vo.OrderPriceVO;

public interface BspOrdersMapper {
	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int countByExample(BspOrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByExample(BspOrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByPrimaryKey(Integer oid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insert(BspOrders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insertSelective(BspOrders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	List<BspOrders> selectByExample(BspOrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	BspOrders selectByPrimaryKey(Integer oid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BspOrders record,
			@Param("example") BspOrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExample(@Param("record") BspOrders record,
			@Param("example") BspOrdersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKeySelective(BspOrders record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_orders
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKey(BspOrders record);

	/**
	 * 获取购物车产品
	 * 
	 * @param priceType
	 * @param type
	 * @param regionsId
	 * @return
	 */
	public List<CartSnapVO> getCartProduct(@Param("userId") int userId,
			@Param("regionId") int regionId);

	/**
	 * 获取区域运费和装卸费
	 */
	public List<OrderPriceVO> getPrice(@Param("regionsId") int regionsId);

	/**
	 * 获取产品的区域价格
	 * 
	 * @param productId
	 * @param regionsId
	 * @param type
	 * @return
	 */
	public String getProductPriceByArea(@Param("productId") int productId,
			@Param("regionsId") int regionsId);

	/**
	 * 查询产品的库存
	 * 
	 * @param productId
	 * @return
	 */
	public Integer getProductStock(@Param("productId") int productId);

	/**
	 * 分页查询订单列表
	 * 
	 * @param startNum
	 * @param limitNum
	 * @return
	 */
	public List<BspOrders> getOrderList(Map<String, Object> params);

	/**
	 * 查询订单总数量
	 * 
	 * @param params
	 * @return
	 */
	public int getOrderCount(Map<String, Object> params);

	/**
	 * 查询运费或装卸费
	 * 
	 * @param regionId
	 * @param priceType
	 * @param type
	 * @return
	 */
	public String getProductRegionPrice(@Param("regionId") int regionId,
			@Param("priceType") int priceType, @Param("type") int type);

	/**
	 * 删除关联订单购物车
	 * 
	 * @param oid
	 * @return
	 */
	public int deleteCompleteCart(int oid);

	public List<BspOrders> selectOrderPage(Map<String, Object> map);

	public int countOrderPage(Map<String, Object> map);

	public List<BspOrders> selectSalerOrderPage(Map<String, Object> map);

	public int countSalerOrderPage(Map<String, Object> map);

	/**
	 * 获取产品的区域运费 装卸费
	 * 
	 * @param productId
	 * @param regionsId
	 * @param type
	 * @return
	 */
	public String getProductPriceByFreight(@Param("productId") int productId,
			@Param("regionsId") int regionsId,
			@Param("priceType") int priceType, @Param("type") int type);

	/**
	 * 获取产品的区域运费 装卸费
	 * 
	 * @param productId
	 * @param regionsId
	 * @param type
	 * @return
	 */
	public List<OrderPriceVO> getCost(@Param("productId") int productId,
			@Param("regionsId") int regionsId, @Param("priceType") int priceType);

	/**
	 * 查询物品
	 * 
	 * @param params
	 * @return
	 */
	public int countProduct(@Param("pid") int pid);

	/**
	 * 根据物品ID查生产厂家
	 * 
	 * @param params
	 * @return
	 */
	public BspProductattributes getManufacturerbyPid(@Param("pid") int pid);

}