package com.runlion.shop.dao;

import com.runlion.shop.entity.BspOrderpricemny;
import com.runlion.shop.entity.BspOrderpricemnyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BspOrderpricemnyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    int countByExample(BspOrderpricemnyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    int deleteByExample(BspOrderpricemnyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    int insert(BspOrderpricemny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    int insertSelective(BspOrderpricemny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    List<BspOrderpricemny> selectByExample(BspOrderpricemnyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    BspOrderpricemny selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspOrderpricemny record, @Param("example") BspOrderpricemnyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    int updateByExample(@Param("record") BspOrderpricemny record, @Param("example") BspOrderpricemnyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    int updateByPrimaryKeySelective(BspOrderpricemny record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_orderpricemny
     *
     * @mbggenerated Wed Sep 09 16:48:51 CST 2015
     */
    int updateByPrimaryKey(BspOrderpricemny record);
}