package com.runlion.shop.dao;

import com.runlion.shop.entity.BspProductimages;
import com.runlion.shop.entity.BspProductimagesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BspProductimagesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int countByExample(BspProductimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int deleteByExample(BspProductimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int deleteByPrimaryKey(Integer pimgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int insert(BspProductimages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int insertSelective(BspProductimages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    List<BspProductimages> selectByExample(BspProductimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    BspProductimages selectByPrimaryKey(Integer pimgid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspProductimages record, @Param("example") BspProductimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int updateByExample(@Param("record") BspProductimages record, @Param("example") BspProductimagesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int updateByPrimaryKeySelective(BspProductimages record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productimages
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int updateByPrimaryKey(BspProductimages record);
}