package com.runlion.shop.dao;

import com.runlion.shop.entity.BspProductsregionssaleaddress;
import com.runlion.shop.entity.BspProductsregionssaleaddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BspProductsregionssaleaddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productsregionssaleaddress
     *
     * @mbggenerated Sat Aug 08 13:01:53 CST 2015
     */
    int countByExample(BspProductsregionssaleaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productsregionssaleaddress
     *
     * @mbggenerated Sat Aug 08 13:01:53 CST 2015
     */
    int deleteByExample(BspProductsregionssaleaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productsregionssaleaddress
     *
     * @mbggenerated Sat Aug 08 13:01:53 CST 2015
     */
    int insert(BspProductsregionssaleaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productsregionssaleaddress
     *
     * @mbggenerated Sat Aug 08 13:01:53 CST 2015
     */
    int insertSelective(BspProductsregionssaleaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productsregionssaleaddress
     *
     * @mbggenerated Sat Aug 08 13:01:53 CST 2015
     */
    List<BspProductsregionssaleaddress> selectByExample(BspProductsregionssaleaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productsregionssaleaddress
     *
     * @mbggenerated Sat Aug 08 13:01:53 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspProductsregionssaleaddress record, @Param("example") BspProductsregionssaleaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_productsregionssaleaddress
     *
     * @mbggenerated Sat Aug 08 13:01:53 CST 2015
     */
    int updateByExample(@Param("record") BspProductsregionssaleaddress record, @Param("example") BspProductsregionssaleaddressExample example);
}