package com.runlion.shop.dao;

import com.runlion.shop.entity.BspProregionextprice;
import com.runlion.shop.entity.BspProregionextpriceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BspProregionextpriceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    int countByExample(BspProregionextpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    int deleteByExample(BspProregionextpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    int insert(BspProregionextprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    int insertSelective(BspProregionextprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    List<BspProregionextprice> selectByExample(BspProregionextpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    BspProregionextprice selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspProregionextprice record, @Param("example") BspProregionextpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    int updateByExample(@Param("record") BspProregionextprice record, @Param("example") BspProregionextpriceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    int updateByPrimaryKeySelective(BspProregionextprice record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_proregionextprice
     *
     * @mbggenerated Tue Sep 01 14:58:03 CST 2015
     */
    int updateByPrimaryKey(BspProregionextprice record);
}