package com.runlion.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspProductsregionspriceLog;
import com.runlion.shop.entity.BspProductsregionspriceLogExample;

public interface BspProductsregionspriceLogMapper {

	int last_insert_id();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	int countByExample(BspProductsregionspriceLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	int deleteByExample(BspProductsregionspriceLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	int insert(BspProductsregionspriceLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	int insertSelective(BspProductsregionspriceLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	List<BspProductsregionspriceLog> selectByExample(
			BspProductsregionspriceLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	BspProductsregionspriceLog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	int updateByExampleSelective(
			@Param("record") BspProductsregionspriceLog record,
			@Param("example") BspProductsregionspriceLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	int updateByExample(@Param("record") BspProductsregionspriceLog record,
			@Param("example") BspProductsregionspriceLogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	int updateByPrimaryKeySelective(BspProductsregionspriceLog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice_log
	 *
	 * @mbggenerated Thu Aug 06 11:23:34 CST 2015
	 */
	int updateByPrimaryKey(BspProductsregionspriceLog record);
}