package com.runlion.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspProductskus;
import com.runlion.shop.entity.BspProductskusExample;
import com.runlion.shop.entity.BspProductskusRTM;

public interface BspProductskusMapper {

	List<BspProductskusRTM> getProductSkuList(int pid);

	List<BspProductskus> getProductSkuListByGroup(int skugid);

	List<BspProductskusRTM> getProductSkuForPreview(int pid);

	List<BspProductskusRTM> getProductSku(int pid);

	List<BspProductskusRTM> getBrandSkuByAreaId(@Param("areaId") int areaId);

	List<BspProductskusRTM> getFactorySkuByBrand(@Param("areaId") int areaId,
			@Param("brandId") int brandId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int countByExample(BspProductskusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByExample(BspProductskusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByPrimaryKey(Integer recordid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insert(BspProductskus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insertSelective(BspProductskus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	List<BspProductskus> selectByExample(BspProductskusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	BspProductskus selectByPrimaryKey(Integer recordid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BspProductskus record,
			@Param("example") BspProductskusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExample(@Param("record") BspProductskus record,
			@Param("example") BspProductskusExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKeySelective(BspProductskus record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productskus
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKey(BspProductskus record);
}