package com.runlion.shop.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspProductsregionsprice;
import com.runlion.shop.entity.BspProductsregionspriceExample;

public interface BspProductsregionspriceMapper {

	// 获取产品的区域价格
	List<BspProductsregionsprice> getProductsregionsPrice(
			@Param("productId") int productId, @Param("regionsId") int regionsId);

	// 区域运费
	List<BspProductsregionsprice> getRegionsTransPrice(
			@Param("regionsId") int regionsId);

	// 区域装卸费
	List<BspProductsregionsprice> getRegionsLoadPrice(
			@Param("regionsId") int regionsId);

	// 获取产品的区域价格
	public List<Map<String, Object>> getProductRegionPrice(
			Map<String, Object> par);

	public int getProductRegionPriceCount(Map<String, Object> par);

	/**
	 * 通过产品id删除相关的价格信息
	 * 
	 * @param pid
	 * @return
	 */
	int deleteByRefRegionsPid(Integer pid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	int countByExample(BspProductsregionspriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	int deleteByExample(BspProductsregionspriceExample example);

	int deleteProductsRegionsHasPid(String ids);

	// 根据产品id批量删除价格
	int deletePriceByProductId(@Param(value = "priceType") Integer priceType,
			@Param(value = "pid") Integer pid);

	List<BspProductsregionsprice> selectPriceByProductId(
			@Param(value = "priceType") Integer priceType,
			@Param(value = "pid") Integer pid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	int insert(BspProductsregionsprice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	int insertSelective(BspProductsregionsprice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	List<BspProductsregionsprice> selectByExample(
			BspProductsregionspriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	BspProductsregionsprice selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	int updateByExampleSelective(
			@Param("record") BspProductsregionsprice record,
			@Param("example") BspProductsregionspriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	int updateByExample(@Param("record") BspProductsregionsprice record,
			@Param("example") BspProductsregionspriceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	int updateByPrimaryKeySelective(BspProductsregionsprice record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_productsregionsprice
	 *
	 * @mbggenerated Thu Jul 02 10:49:04 CST 2015
	 */
	int updateByPrimaryKey(BspProductsregionsprice record);
}