package com.runlion.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspRegions;
import com.runlion.shop.entity.BspRegionsExample;

public interface BspRegionsMapper {

	// <!-- 获取工厂、门店的覆盖区域 -->
	public List<BspRegions> getSaleAddressRegions(int saleaddressId);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int countByExample(BspRegionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByExample(BspRegionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByPrimaryKey(Integer regionid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insert(BspRegions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insertSelective(BspRegions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	List<BspRegions> selectByExample(BspRegionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	BspRegions selectByPrimaryKey(Integer regionid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BspRegions record,
			@Param("example") BspRegionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExample(@Param("record") BspRegions record,
			@Param("example") BspRegionsExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKeySelective(BspRegions record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_regions
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKey(BspRegions record);
}