package com.runlion.shop.dao;

import com.runlion.shop.entity.BspShipaddresses;
import com.runlion.shop.entity.BspShipaddressesExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BspShipaddressesMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int countByExample(BspShipaddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int deleteByExample(BspShipaddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int deleteByPrimaryKey(Integer said);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int insert(BspShipaddresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int insertSelective(BspShipaddresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    List<BspShipaddresses> selectByExample(BspShipaddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    BspShipaddresses selectByPrimaryKey(Integer said);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspShipaddresses record, @Param("example") BspShipaddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int updateByExample(@Param("record") BspShipaddresses record, @Param("example") BspShipaddressesExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int updateByPrimaryKeySelective(BspShipaddresses record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_shipaddresses
     *
     * @mbggenerated Fri Jun 26 14:56:27 CST 2015
     */
    int updateByPrimaryKey(BspShipaddresses record);
}