package com.runlion.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspSaleaddress;
import com.runlion.shop.entity.BspSaleaddressExample;

public interface BspSaleaddressMapper {
	BspSaleaddress getProductStore(@Param(value = "regionId") int regionId);

	BspSaleaddress getProductFactory(@Param(value = "regionId") int regionId,
			@Param(value = "placeId") int placeId);

	/**
	 * 根据收货地址获取门店地址和工厂地址
	 * 
	 * @param type
	 * @param shipaddressesId
	 * @return
	 */
	public List<BspSaleaddress> getSaleaddress(
			@Param("shipaddressesId") int shipaddressesId);

	/**
	 * 根据收货地址获取门店地址和工厂地址
	 * 
	 * @param type
	 * @param shipaddressesId
	 * @return
	 */
	public List<BspSaleaddress> getSaleaddressByRid(
			@Param("regionsId") int shipaddressesId, @Param("type") int type);

	/**
	 * 根据收货地址获取门店地址和工厂地址
	 * 
	 * @param type
	 * @param shipaddressesId
	 * @return
	 */
	public List<BspSaleaddress> getAddressNotype(
			@Param("regionsId") int shipaddressesId);

	/**
	 * 根据收货地址获取门店地址和工厂地址
	 * 
	 * @param type
	 * @param shipaddressesId
	 * @return
	 */
	public List<BspSaleaddress> getSaleaddressByRegId(
			@Param("shipaddressesId") int shipaddressesId,
			@Param("type") int type);

	public List<BspSaleaddress> selectall();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int countByExample(BspSaleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int deleteByExample(BspSaleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int insert(BspSaleaddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int insertSelective(BspSaleaddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	List<BspSaleaddress> selectByExampleWithBLOBs(BspSaleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	List<BspSaleaddress> selectByExample(BspSaleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	BspSaleaddress selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BspSaleaddress record,
			@Param("example") BspSaleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int updateByExampleWithBLOBs(@Param("record") BspSaleaddress record,
			@Param("example") BspSaleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int updateByExample(@Param("record") BspSaleaddress record,
			@Param("example") BspSaleaddressExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int updateByPrimaryKeySelective(BspSaleaddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int updateByPrimaryKeyWithBLOBs(BspSaleaddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_saleaddress
	 *
	 * @mbggenerated Mon Sep 07 10:14:49 CST 2015
	 */
	int updateByPrimaryKey(BspSaleaddress record);
}