package com.runlion.shop.dao;

import com.runlion.shop.entity.BspUserApply;
import com.runlion.shop.entity.BspUserApplyExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BspUserApplyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    int countByExample(BspUserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    int deleteByExample(BspUserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    int insert(BspUserApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    int insertSelective(BspUserApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    List<BspUserApply> selectByExample(BspUserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    BspUserApply selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspUserApply record, @Param("example") BspUserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    int updateByExample(@Param("record") BspUserApply record, @Param("example") BspUserApplyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    int updateByPrimaryKeySelective(BspUserApply record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_user_apply
     *
     * @mbggenerated Wed Sep 02 09:37:19 CST 2015
     */
    int updateByPrimaryKey(BspUserApply record);
}