package com.runlion.shop.dao;

import com.runlion.shop.entity.BspUsersPermission;
import com.runlion.shop.entity.BspUsersPermissionExample;
import com.runlion.shop.entity.BspUsersPermissionWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BspUsersPermissionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int countByExample(BspUsersPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int deleteByExample(BspUsersPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int insert(BspUsersPermissionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int insertSelective(BspUsersPermissionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    List<BspUsersPermissionWithBLOBs> selectByExampleWithBLOBs(BspUsersPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    List<BspUsersPermission> selectByExample(BspUsersPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    BspUsersPermissionWithBLOBs selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspUsersPermissionWithBLOBs record, @Param("example") BspUsersPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int updateByExampleWithBLOBs(@Param("record") BspUsersPermissionWithBLOBs record, @Param("example") BspUsersPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int updateByExample(@Param("record") BspUsersPermission record, @Param("example") BspUsersPermissionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int updateByPrimaryKeySelective(BspUsersPermissionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int updateByPrimaryKeyWithBLOBs(BspUsersPermissionWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_users_permission
     *
     * @mbggenerated Fri Aug 28 17:18:32 CST 2015
     */
    int updateByPrimaryKey(BspUsersPermission record);
}