package com.runlion.shop.dao;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.BspUsers;
import com.runlion.shop.entity.BspUsersExample;

public interface BspUsersMapper {

	public Map<String, Object> selectUuidParams(Map<String, Object> par);

	public void insertUuidParams(Map<String, Object> par);

	public void updateUserPwd(Map<String, Object> par);

	public Map<String, Object> selectUserByLoginname(Map<String, Object> par);

	public void insertUserDetails(Map<String, Object> par);

	public void insertUser(Map<String, Object> par);

	public Integer getUserMaxId();

	public int hasSameUsername(Map<String, Object> par);

	public Map<String, Object> selectUserEffect(Map<String, Object> par);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int countByExample(BspUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByExample(BspUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int deleteByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insert(BspUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int insertSelective(BspUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	List<BspUsers> selectByExample(BspUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	BspUsers selectByPrimaryKey(Integer uid);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExampleSelective(@Param("record") BspUsers record,
			@Param("example") BspUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByExample(@Param("record") BspUsers record,
			@Param("example") BspUsersExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKeySelective(BspUsers record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table bsp_users
	 *
	 * @mbggenerated Fri Jun 26 14:56:27 CST 2015
	 */
	int updateByPrimaryKey(BspUsers record);
	
	
	
	List<Map<String,Object>> selectByExamplePrice(Map<String, Object> par);
}