package com.runlion.shop.dao;

import com.runlion.shop.entity.BspUsercarinfor;
import com.runlion.shop.entity.BspUsercarinforExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BspUsercarinforMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    int countByExample(BspUsercarinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    int deleteByExample(BspUsercarinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    int insert(BspUsercarinfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    int insertSelective(BspUsercarinfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    List<BspUsercarinfor> selectByExample(BspUsercarinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    BspUsercarinfor selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    int updateByExampleSelective(@Param("record") BspUsercarinfor record, @Param("example") BspUsercarinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    int updateByExample(@Param("record") BspUsercarinfor record, @Param("example") BspUsercarinforExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    int updateByPrimaryKeySelective(BspUsercarinfor record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bsp_usercarinfor
     *
     * @mbggenerated Wed Sep 09 15:07:36 CST 2015
     */
    int updateByPrimaryKey(BspUsercarinfor record);
}