package com.runlion.shop.dao;

import com.runlion.shop.entity.SysUsercontext;
import com.runlion.shop.entity.SysUsercontextExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SysUsercontextMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    int countByExample(SysUsercontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    int deleteByExample(SysUsercontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    int insert(SysUsercontext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    int insertSelective(SysUsercontext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    List<SysUsercontext> selectByExample(SysUsercontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    SysUsercontext selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    int updateByExampleSelective(@Param("record") SysUsercontext record, @Param("example") SysUsercontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    int updateByExample(@Param("record") SysUsercontext record, @Param("example") SysUsercontextExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    int updateByPrimaryKeySelective(SysUsercontext record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table SYS_USERCONTEXT
     *
     * @mbggenerated Tue Sep 01 13:29:07 CST 2015
     */
    int updateByPrimaryKey(SysUsercontext record);
}