package com.runlion.shop.dao;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.runlion.shop.entity.Unionpayresult;
import com.runlion.shop.entity.UnionpayresultExample;
import com.runlion.shop.entity.unionpay.UnionPayResult;

public interface UnionpayresultMapper {

	int insertBankInfo(UnionPayResult record); // 注意实体跟别的方法不一样！！

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	int countByExample(UnionpayresultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	int deleteByExample(UnionpayresultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	int insert(Unionpayresult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	int insertSelective(Unionpayresult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	List<Unionpayresult> selectByExample(UnionpayresultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	Unionpayresult selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	int updateByExampleSelective(@Param("record") Unionpayresult record,
			@Param("example") UnionpayresultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	int updateByExample(@Param("record") Unionpayresult record,
			@Param("example") UnionpayresultExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	int updateByPrimaryKeySelective(Unionpayresult record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds
	 * to the database table unionPayResult
	 *
	 * @mbggenerated Wed Aug 26 10:04:59 CST 2015
	 */
	int updateByPrimaryKey(Unionpayresult record);
}